### ISSUE TITLE
Different Output  from Log.txt

### ISSUE THREAD

**Issue by ElaineResende** [iit-cs429/main#100]
I am having a problem, probably with the distance function, but I am not sure. The error comes wrong and after the 3 iteration the clusters are different. My output is below. Could anybody give me some hint about what can be happening?

Thank you. :)

Output:

read 10000 profiles.
defaultdict(<type 'int'>, {0: 4, 1: 5, 2: 673, 3: 23, 4: 2, 5: 8, 6: 727, 7: 200
, 8: 7817, 9: 354})
35676.1465938
defaultdict(<type 'int'>, {0: 12, 1: 17, 2: 755, 3: 152, 4: 3, 5: 23, 6: 753, 7:
 456, 8: 6982, 9: 660})
31639.6349844
defaultdict(<type 'int'>, {0: 19, 1: 62, 2: 706, 3: 279, 4: 4, 5: 41, 6: 859, 7:
 610, 8: 6374, 9: 859})
31383.1457996
defaultdict(<type 'int'>, {0: 42, 1: 88, 2: 661, 3: 310, 4: 7, 5: 52, 6: 860, 7:
 787, 8: 5948, 9: 1058})
31228.653268
defaultdict(<type 'int'>, {0: 70, 1: 121, 2: 637, 3: 327, 4: 17, 5: 64, 6: 879,
7: 880, 8: 5684, 9: 1134})
31125.6990248
defaultdict(<type 'int'>, {0: 119, 1: 188, 2: 623, 3: 345, 4: 51, 5: 75, 6: 849,
 7: 970, 8: 5446, 9: 1147})
31066.1344588
defaultdict(<type 'int'>, {0: 239, 1: 243, 2: 598, 3: 344, 4: 161, 5: 88, 6: 787
, 7: 942, 8: 5225, 9: 1186})
30972.8167823
defaultdict(<type 'int'>, {0: 297, 1: 299, 2: 594, 3: 340, 4: 200, 5: 102, 6: 70
5, 7: 921, 8: 5176, 9: 1179})
30888.7967466
defaultdict(<type 'int'>, {0: 291, 1: 397, 2: 591, 3: 341, 4: 223, 5: 114, 6: 66
6, 7: 909, 8: 5121, 9: 1160})
30864.7521698
defaultdict(<type 'int'>, {0: 292, 1: 462, 2: 597, 3: 342, 4: 247, 5: 129, 6: 63
0, 7: 900, 8: 5080, 9: 1134})
30842.4344176

**Comment by adityashirodkar** [comment]
Recompute the mean before calculating the error.

**Comment by ElaineResende** [comment]
I have done that.

**Comment by pcastrotigre** [comment]
I am having the same problem.

Please, could any of you who has already done, send a print of the distances of some documents in the first iteration? So I can compare and debug the error.

**Comment by vivekpabani** [comment]
Follow below steps -
1. compute_clusters
2. compute_means
3. compute the distance of each document from the newly assigned cluster mean.
4. compute_error by adding these new distances.

The wrong error values may be due to old distance values.

**Comment by pcastrotigre** [comment]
Yes, I am doing that but if I get a wrong error distance in the first iteration, so I will have in the others too. 

I would like to get some distances of some documents in the first iteration, because my error distance is wrong, however counts are correct for the clusters for the first iteration.

This is the output of the first iteration
[4, 5, 673, 23, 2, 8, 727, 200, 7817, 354]
34890.5667809
