### ISSUE TITLE
Term order in cluster docs output

### ISSUE THREAD

**Issue by arunakanagaraj** [iit-cs429/main#101]
Hi

I get matching results for length of cluster, mean error and the cluster documents.

However, the term order in the document printed is different from that in Log.txt for few documents (not all documents)
For example:
In Log.txt, it is 'and of life the times' and in my output, it is 'and life of times the'

Is anyone else facing this issue? Can you please let me know if there is any particular basis on which the terms need to be sorted.?

Also, two documents in cluster 0 alone are jumbled in order.

Thanks,
Aruna K

**Comment by aronwc** [comment]
Don't worry about document order. Counter.keys() may return values in an
inconsistent order.
-Aron

**Comment by arunakanagaraj** [comment]
Thank you.
