### ISSUE TITLE
Assignment 6 Data Access Issue

### ISSUE THREAD

**Issue by arunakanagaraj** [iit-cs429/main#104]
Dear Professor,

I am getting the following access error on trying to download input data from http://cs.iit.edu/~culotta/cs429/asg6.zip

>>
403 Forbidden Access

Access to the requested resources was forbidden due to permission settings or security restrictions. The file may not have the required permissions or your computer may be outside the allowed domain.
>>

Can you please help give permission to access the data?

Thanks,
Aruna K

**Comment by dougcirqueira** [comment]
I've got the same. I think the professor is going to open the link.

**Comment by aronwc** [comment]
OK, it should work now.
