### ISSUE TITLE
Final exam - Linear regression

### ISSUE THREAD

**Issue by ElaineResende** [iit-cs429/main#109]
Hi Aron,

What kind of question should we expect related to Linear Regression?

Thank you.

**Comment by aronwc** [comment]
- You should be prepared to update parameters given data and the update
equation.
- You should understand how the update equation works, and how it is
related to the cost function.
- You should be prepared to interpret modifications to the cost function
and/or update equation.

**Comment by ElaineResende** [comment]
Thank you.
