### ISSUE TITLE
Clarification required in smoothing 

### ISSUE THREAD

**Issue by bpraveen92** [iit-cs429/main#111]
hi, can anyone give me the exact formula to calculate both Multinomial and Bernoulli Naive Bayes when asked to estimate along with smoothing ?
I assume for bernoulli naive bayes it is 
(count of docs that contain a particular word in class A + epsilon) / (total count of class A docs + 2*epsilon)
and for Multinomial it is
(Count of number of occurrences of a particular word under class label A + epsilon) / (Total count of words under Class A + Total count of unique words in all class labels * epsilon)

Am I right here ?

**Comment by aronwc** [comment]
Correct.
