### ISSUE TITLE
Finals review questions.

### ISSUE THREAD

**Issue by canichet** [iit-cs429/main#112]
Has anyone solved the practice questions for the finals ?
The answers I am getting are - 

 6) a) 

points assigned to  µ1 = {x1,x2,x4}
points assigned to µ2 = {x3}.

new means ->  µ1 = (-5/3 , 0) and µ2 = (3 , 2)

@aronwc Professor if the means are in fraction the below representation is enough ?

6) b)   the error is e1 + e2
Where 
e1 = sqrt((-(5/3)-4)^2 + (-2)^2) + sqrt ((-(5/3)+2)^2 + (1)^2)  + sqrt ((-(5/3)-1)^2 + (1)^2) 
e2 = sqrt((3-3)^2 + (3-2)^2)

7) a) apple      11/19  3/9
        orange     8/19   6/9

b) ~ 0.379

**Comment by sjain41** [comment]
I have same answers for 6

**Comment by arunakanagaraj** [comment]
I am also confused with the 7b solution. Can anyone help understand the correct calculation for classification probability in multinomial method?

**Comment by FilipeTabosa** [comment]
my 7b solution was ~ 0.378. I got (3/5 * 8/19 * 8/19) / ((3/5 * 8/19 * 8/19)+ (2/5 * 2/3 * 2/3)). But I am not sure if I did it right.

**Comment by canichet** [comment]
Yes matches mine!

**Comment by sjain41** [comment]
whys is the middle term P(apple=0 | y=1) = 8/19? from what i thought, its probability that apple is not appearing in y=1. is that correct?

**Comment by FilipeTabosa** [comment]
If P(apple=1| y=1) = 11/19, then P(apple=0| y=1) = 8/19

**Comment by sjain41** [comment]
makes sense. thank you

**Comment by sjain41** [comment]
does anyone have questions for KNN, Logistic regression to practice? i listened to lectures but wondering how will quesetion look like in exam

**Comment by Datguyovrder** [comment]
For some reason I keep getting error 2 as 0 when using the new mean (3,2).

**Comment by benjaminwalters** [comment]
I got the same answer as @Datguyovrder. It makes sense since the mean is the same as the point.

**Comment by vivekpabani** [comment]
One confusion about 7-b. If we are using Multinomial Naïve Bayes, shouldn't we just ignore the term which is not in the document? The lecture note says - "Note that in Multinomial Naive Bayes, to classify a new document, we only multiply terms that occur in the document". So, shouldn't we ignore the term apple = 0?

**Comment by ElaineResende** [comment]
I think so @vivekpabani. Nonoccurence of terms does not affect Bernoulli.

**Comment by aronwc** [comment]
For multinomial Naive Bayes, please see section [13.2 of your text](http://nlp.stanford.edu/IR-book/pdf/13bayes.pdf).
