### ISSUE TITLE
Sample Questions 7-b

### ISSUE THREAD

**Issue by vivekpabani** [iit-cs429/main#116]
One confusion about 7-b. If we are using Multinomial Naïve Bayes, shouldn't we just ignore the term which is not in the document? The lecture note says - "Note that in Multinomial Naive Bayes, to classify a new document, we only multiply terms that occur in the document". So, shouldn't we ignore the term apple = 0?

**Comment by aronwc** [comment]
yes, you ignore apple=0 when doing classification in multinomial naive bayes.

**Comment by vivekpabani** [comment]
Thank you! :)
