### ISSUE TITLE
index.py: create_tf_index()

### ISSUE THREAD

**Issue by changediyasunny** [iit-cs429/main#121]
1. In comments, it is mentioned that       index[term] = [doc_id, tf weight]
2. In doctest, the tests seems to have    index['a'] = [doc_id, tf ]

Are tf & tf-weight are same ? that is term frequency ? or is it 1+log(tf)  ??

if we were to calculate tf-weight, then doctest will probably fail, because log10 cannot be integer value?

**Comment by skrzepto** [comment]
+1 I'm also confused with this function comments

**Comment by aronwc** [comment]
Here, you should just use the raw term frequency, without the log transformation. 

The goal is to create one index, which can be used by each of the scoring functions in `score.py`. Not all of them use the (1 + log(tf)) transformation.
