### ISSUE TITLE
A2: trouble with doctests for Scores

### ISSUE THREAD

**Issue by skrzepto** [iit-cs429/main#122]
I was working on RSV and noticed that the repr function was not returning the string so we can get the float in the 1st index like the doctests suggest but I'm getting an error 

```
File "cs429/a2/score.py", line 65, in score.RSV
Failed example:
    rsv.score({'a': 1.}, idx)[1]  # doctest:+ELLIPSIS
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1324, in __run
        compileflags, 1), test.globs)
      File "<doctest score.RSV[2]>", line 1, in <module>
        rsv.score({'a': 1.}, idx)[1]  # doctest:+ELLIPSIS
    TypeError: 'float' object is not subscriptable
```

Its as if only the float is being returned and that 

```
        rsv.score({'a': 1.}, idx)[1]  # doctest:+ELLIPSIS
```
Solved:

I was computing only one docs value and returning it when it needs to be a dict of doc_id values

**Comment by changediyasunny** [comment]
I don't think it is with Doctests, But You might be passing index value as float to somewhere in your code.

**TypeError: 'float' object is not subscriptable** is when you try to index into LIST with float value. Should be integer index

**Comment by skrzepto** [comment]
Well when I remove the [1]
`rsv.score({'a': 1.}, idx)  # doctest:+ELLIPSIS`

The test passes.

My understanding was that repr should have fired on rsv.score to return to the console
['RSV', 0.4771]

which is why we access the [1] element for the value. 

unless we are supposed to be returning two values in the rsv function I think there might be something off in the doctest

**Comment by aronwc** [comment]
No, repr is not used in the .score method. Score returns a dict from document id (an int) to relevance score (a float). So, the [1] in `rsv.score({'a': 1.}, idx)[1]` is returning the score for the first document ('a b c'). Note that, to be compatible with the numbering in the data files, **document ids start at 1**.

**Comment by changediyasunny** [comment]
Prof,
yes. that was taken care of.

But doctest presents answer as 0.477..., while I am getting answer as 0.477 after using round () function. and it sayd Test Failed???? any suggestion?

**Comment by aronwc** [comment]
No need to use the round function. The "0.477..." notation indicates that there are numbers after the final 7. You're rounded versions will not.

**Comment by changediyasunny** [comment]
then I am having answer as 0.47712564876 and still test seems Failed?

**Comment by aronwc** [comment]
I assume the test still looks like this:
```python
>>> rsv.score({'a': 1.}, idx)[1]  # doctest:+ELLIPSIS
0.4771...
```
That should pass. Check in your code if you want me to look.
