### ISSUE TITLE
score.py : Cosine.score()

### ISSUE THREAD

**Issue by changediyasunny** [iit-cs429/main#123]
Prof,

In A1, to calculate Cosine similarity, we used 
Cosine_sim = (tf-idf of query * tf-idf of doc)/length-normalization

But in A2,  query vector is only tf of query. So how should we calculate Cosine similarity?

is it like Cosine_sim = (tf of query * tf-idf of doc) ??? Confused over this.

**Comment by aronwc** [comment]
You will have to transform the raw tf values for the query into our typical (1 + log(tf))*idf  values.

**Comment by changediyasunny** [comment]
ohh. So transformation is needed. 
It wasn't mentioned in comments. I will make changes

**Comment by changediyasunny** [comment]
Prof,
in A2,   query_vector ----> idf values,  and index---> tf values.

so to calculate Cosine score():  do we have to transform query_vector--->(tf-idf weight)
and Index ---> (tf-idf weight) and then calculate Cosine similarity between them????

because then both will represent tf-idf weight?
