### ISSUE TITLE
What does RSV.score return is it an array or a hash?

### ISSUE THREAD

**Issue by JamalK** [iit-cs429/main#129]
Also, is the index starting with 0? or 1, should I prepend it like [0] + my_values, or what does the index in this case mean? thanks.

**Comment by changediyasunny** [comment]
As Prof. mentioned, 
index automatically starts from 1 as input file contains doc_id starting at 1.
so in your code make sure you have starting index 1 and not 0. do not cahnge doctest. they are correct. RSV.score returns a dict mapping doc_id to RSV value for query

**Comment by JamalK** [comment]
Thanks! @changediyasunny
