### ISSUE TITLE
create_tf_index in index.py

### ISSUE THREAD

**Issue by cgarciahdez** [iit-cs429/main#130]
I am a little confused with the parameters of this function. Why do we need the doc_freqs here? Are they useful at some point?

**Comment by mseryn** [comment]
I was having similar thoughts and didn't use doc_freqs to implement create_tf_index.

**Comment by cgarciahdez** [comment]
I did the same, it just seemed weird to have it as a parameter if we shouldn't use it. I was wondering if maybe I did something wrong.

**Comment by aronwc** [comment]
You're right -- you don't need to use doc_freqs in create_tf_index.

**Comment by karthikbmk** [comment]
Another doubt in the same function.  Comment says :
'the term 'b' appears in document 5 (with **tf-idf** weight 1)' .  Isn't it just tf and not tf-idf ?

**Comment by cgarciahdez** [comment]
I think it would be, as you don't need docfreqs, and you would need it to use tf-idf
