### ISSUE TITLE
query_to_vector in index.py

### ISSUE THREAD

**Issue by cgarciahdez** [iit-cs429/main#131]
I am getting the following mistake:

File "/Users/camilagarciahernandez/Documents/Universidad/Iit/infret/cgarciahdez/a2/index.py", line 175, in index.Index.query_to_vector
Failed example:
    idx.query_to_vector(['a', 'a']) # doctest:+ELLIPSIS
Expected:
    {'a': 0.477...}
Got:
    defaultdict(<class 'float'>, {'a': 0.47712125471966244})

Should I not return a defaultdict? Do I have to return a normal dictionary?

**Comment by Brownie79** [comment]
you can easily instance a regular dictionary by using
variable_name = {}

I just use that to instance regular dictionaries and that seems to work for all methods that ask for a dict

**Comment by aronwc** [comment]
Yes, please just use a regular dict here.
