### ISSUE TITLE
Scores

### ISSUE THREAD

**Issue by cgarciahdez** [iit-cs429/main#133]
I am having a hard time understanding exactly what I should use to calculate each score.
Today I talked to you and you told me the query vector already has the idf score for each vector, but in the comments for the RSV score it says that the idf score is different:

"""
    See lecture notes for definition of RSV.

    idf(a) = log10(3/1)
    idf(d) = log10(3/1)
    idf(e) = log10(3/2)
    >>> idx = index.Index(['a b c', 'c d e', 'c e f'])
    >>> rsv = RSV()
    >>> rsv.score({'a': 1.}, idx)[1]  # doctest:+ELLIPSIS
    0.4771...
    """

But if the query vector already had the idf score, wouldn't the input be {'a':log10(3/1)}?

**Comment by aronwc** [comment]
In the tests, I'm using sample values of the query vector that were not produced by query_to_vector. This is to make it simpler to test.

When you run your program on the real data, the main.search method will call query_to_vector to convert a string of query tokens into an IDF vector. The scoring functions do not need to call query_to_vector directly.

**Comment by cgarciahdez** [comment]
But then the rsv score for document one in the doctest would be the idf value, which is one, multiplied by tf, which is also one, and the result would be one, right? 

The only way I'm getting 0.477 is transforming the one by doing log10(n/1), but that assumes the query has the df, not the idf. And it would fail in other cases, because im transforming it, right?

**Comment by mseryn** [comment]
I am also having similar concerns.
The doctest is as follows:

```
    idf(a) = log10(3/1)
    idf(d) = log10(3/1)
    idf(e) = log10(3/2)
    >>> idx = index.Index(['a b c', 'c d e', 'c e f'])
    >>> rsv = RSV()
    >>> rsv.score({'a': 1.}, idx)[1]  # doctest:+ELLIPSIS
    0.4771...
```

This states the IDF value for 'a' is 1.  The IDF value for 'a' is not 1, but this would be okay if the returned value from the function were not 0.4771, as this value is the correct retrieval status value for document 1 and query 'a'.  RSV is the sum, per document, of IDF values for all queries matching that document.  If the IDF for 'a' were 1, then the RSV for query 'a' on document 1 would be 1, not 0.4771.

**Comment by cgarciahdez** [comment]
Exact same thing happening to me. I'm afraid that by forcing it to work with the doctest, I will be making it wrong for all other searches that do have the idf number in the query vector

**Comment by aronwc** [comment]
I think I see the confusion now.

While you don't need to call query_to_vector from RSV.score(), you do need to call the idf(term, index) function. My thought was to make the scoring function work the same no matter what values were passed into the query_vector.

**Comment by mseryn** [comment]
Can you clarify what the parameter query_vector contains?  Is it a dict mapping a term to its document frequency?  If we already have the query-IDF vector in main(), why not pass it in?  More succinctly, what else aside from {term: IDF} might be passed into query_vector in RSV?

**Comment by aronwc** [comment]
When running the main method in this assignment, query_vector will always be a dict from a term in the query to its IDF value: log10(N / df_t), for term t.

I allowed a different value to be passed in for testing purposes only, but clearly this has caused confusion. 

More generally, we may want our scoring functions to be flexible enough to handle different sorts of inputs (e.g., if you want to try using only raw term frequency to represent the query). But, you don't need to worry about that for this assignment.

**Comment by cgarciahdez** [comment]
Im afraid I dont understand still. To do this, do we need to call log at any point? How can we only transform the doctest?

**Comment by mseryn** [comment]
Thank you for clarifying.

If I'm understanding correctly, if main() will always pass in query_vector in the form of a query-IDF vector (such as what query_to_vector() produces from index.py), then we should allow our doctest to fail, as calling idf() from score.py on the value (representing the IDF of a query term) would be redundant.  Does this sound correct?

**Comment by aronwc** [comment]
No, the test should not fail.

In RSV.score, iterate over each term in the query and compute its IDF value by calling idf(term, index). The score for a document is the sum of IDF values for the query terms it contains.

The values in the query_vector dict are ignored, but its keys are still used.

**Comment by aronwc** [comment]
@cgarciahdez Yes, math.log10 will be called  inside of the idf() function, which is called when computing the IDF value for each term in query_vector (see above).

**Comment by mseryn** [comment]
So to be clear, we are to ignore IDF values passed in to the function in query_vector (since query_vector, for our program, will always be a query-IDF vector).  Instead, we re-calculate all IDF values in the term each time RSV is called.  Is this correct?

**Comment by aronwc** [comment]
Correct.

**Comment by mseryn** [comment]
Thank you.

**Comment by Zephan92** [comment]
I followed all of the above, but what exactly is being returned by the
function? A single value or a Dictionary with each key from the
query_vector?

On Thu, Mar 3, 2016 at 11:29 PM, Melanie Cornelius <notifications@github.com

**Comment by aronwc** [comment]
The .score() functions should all return a dict from document id to score.

**Comment by Zephan92** [comment]
Aha, thank you.

**Comment by cgarciahdez** [comment]
Thank you
