### ISSUE TITLE
A2: clarrification in README.md

### ISSUE THREAD

**Issue by skrzepto** [iit-cs429/main#134]
At the bottom of the file there's

> - Compute precision/recall/F1 using only the top 10 results
> - When computing MAP, if a relevant document is not in the top 10, assume 0% precision for those relevant documents.

Does this mean that we only pass in the top 10 results as parameters or do we need to calculate the top 10 results in the function?

**Comment by aronwc** [comment]
Pass in top 10 results as parameters. That's what is happening in the main.run_all function:

```python
hits = search(qtext, scorer, indexer)[:NHITS]
...
for evaluator in evaluators:
                evaluation = evaluator.evaluate(hits, relevant)
```
The `hits` variable has been truncated to the top 10 results.

So, perhaps a more clear way of stating that would be:
>  When computing MAP, if a relevant document is not in the **hits variable**, assume 0% precision for those relevant documents.

This is just the normal definition of MAP we've used in class.

**Comment by skrzepto** [comment]
Thanks that cleared it up.
