### ISSUE TITLE
A2: Claification

### ISSUE THREAD

**Issue by tmarkov** [iit-cs429/main#135]
In file index, method Index().count_doc_frequencies, why are we expected to return floating point numbers? Are you going to deduct point for returning integers instead (document frequencies are integers).

**Comment by aronwc** [comment]
It's true they don't have to be floats, but please make them so for this assignment.

**Comment by tmarkov** [comment]
Another question:
Why do we need doc_freqs as an argument to create_tf_index? Is it redundant, or am I missing something? Also, can you confirm that the following is true: for this assignment, the tf weight is the number of times the word appears in a document, and not 1+log(tf).

**Comment by aronwc** [comment]
> Why do we need doc_freqs as an argument to create_tf_index? Is it redundant
It's redundant (See #130)

>Also, can you confirm that the following is true: for this assignment, the tf weight is the number of times the word appears in a document, and not 1+log(tf).

For Index.create_tf_index, the value inserted is simply tf_{td}; i.e., the number of times term t appears in document d.

For Index.compute_doc_norms and score.Cosine, you will use the full tf-idf transformation: 
`(1 + log10(tf)) * log10(N/df)`
