### ISSUE TITLE
Probabilistic IR, Part I 

### ISSUE THREAD

**Issue by karthikbmk** [iit-cs429/main#139]
In Probabilistic IR, Part I :

![image](https://cloud.githubusercontent.com/assets/8171762/13561044/abd2b902-e3dc-11e5-84b9-634dcd3f300c.png)

I think it should be :
pi : probability of seeing word **i** in a document that is relevant to the query.

since i refers to actual term and xi is just a binary indicator for that term.

**Comment by aronwc** [comment]
Sure. I've referred to these interchangeably throughout. The meaning should hopefully be clear from context.
