### ISSUE TITLE
Midterm practice question 2

### ISSUE THREAD

**Issue by cgarciahdez** [iit-cs429/main#140]
In this question, it is said that there are 100 relevant documents. When computing MAP, would we have to divide by 100? wouldn't we need to know further ranks to do this, to know if other relevant documents were returned, or should we assumed only these 8 were returned?

**Comment by aronwc** [comment]
Yes, divide by 100. Assume 8 is all the documents returned.

**Comment by cgarciahdez** [comment]
Thankyou!
