### ISSUE TITLE
A3: Clarrification on traning function figure 13.2

### ISSUE THREAD

**Issue by skrzepto** [iit-cs429/main#142]
![selection_314](https://cloud.githubusercontent.com/assets/3166193/13902794/35195eba-ee27-11e5-99c5-bb0ca3b1fad4.png)

Line 10: what does Tct' stand for? The denominator and what is being summed actually.

also for condprob[t][c] would an example be condprob['zebra']['ham'] ?

**Comment by aronwc** [comment]
See p.259 (Ch13) of your book:

> where `T_ct` is the number of occurrences of `t` in training documents from class
`c`, including multiple occurrences of a term in a document.


> also for condprob[t][c] would an example be condprob['zebra']['ham'] ?

Yes.

**Comment by skrzepto** [comment]
I understand where T_ct comes from but what does the prime mean on the term occurrences? 

After reading a few pages around that figure my hunch is telling me its the sum of all other Term counts in the class. 

So an example 

ham = {'zebra' : 4, 'dog' : 3, 'cat' :9}

it would be  (4+1)/((3+1)+(9+1)) ?

**Comment by aronwc** [comment]
Yes, `t'` is just an iterator over all terms, as you say, but it also includes the original term.

So, in your example, zebra would also appear in the denominator.

The reason is we need `condprob[t]['ham']` to sum to 1 for all t.

**Comment by skrzepto** [comment]
Okay it's like what the chapter says its the frequency of the term in the class. Thank you for clarifying

**Comment by skrzepto** [comment]
Just want to confirm my understand of conditional prob with this small example



Doc# = [class, [tokes]]
Doc1 = ['spam', [a,b]]
Doc2 = [spam, [b, c]]
Doc3 = [ham, [c, d]]


prior = {'spam': 2/3, 'ham', 1/3}


Tct ['spam'] = {a: 1, b: 2, c:1}  # do we include d?
Tct['ham'] = {c: 1, d: 1}  # do we include a, b?

Spam_Tct_sum = 4 + 3
Ham_Tct_sum = 2 +2

condprob['spam'] = {a: 2/7, b: 3/7,c 2/7}
condporb['ham'] = {c: 2/4, d: 2/4}
