### ISSUE TITLE
A3: Question about doctest

### ISSUE THREAD

**Issue by skrzepto** [iit-cs429/main#143]
Is it okay if I swapped the doctest results from being the (score, term) to (term, score) because the dictionary I use to calculate this returns the values like that.

Failure
**********************************************************************
File "/cs429/a3/classify.py", line 91, in get_top_words
Failed example:
    nb.get_top_words('spam', 2)
Expected:
    [(2.25, 'b'), (1.5, 'a')]
Got:
    [('b', 2.25), ('a', 1.5)]

**Comment by aronwc** [comment]
Please have your output match the original tests.
