### ISSUE TITLE
A3: Question about the Output

### ISSUE THREAD

**Issue by karthikshivaram24** [iit-cs429/main#144]
Is anyone else getting a similar output like this ??
![image](https://cloud.githubusercontent.com/assets/16641182/13966853/61cc17be-f042-11e5-9891-390c3d09b584.png)

**Comment by skrzepto** [comment]
When you run

`python3 classify.py > my_res.txt`

then do

`vimdiff my_res.txt Log.txt` 

To see what different from the accepted results and your output.

It looks like your accuracy is higher and you have one less false spam from accepted results

**Comment by dakshaau** [comment]
I am getting this:

```
read 1893 training documents.
read 1000 testing documents.
accuracy=0.984, 11 false spam, 5 missed spam
top ham terms: 758.80/linguistics 536.90/languages 414.36/workshop 337.17/language 327.82/linguistic 282.82/theory 240.24/grammar 221.89/syntax 204.58/abstracts 194.89/papers
top spam terms: 563.31/&nbsp 398.65/capitalfm 274.43/floodgate 242.66/investment 196.44/bonus 173.33/secrets 170.44/stealth 167.55/millions 160.04/bulk 138.66/mlm
```
