### ISSUE TITLE
A3: Base of LOG

### ISSUE THREAD

**Issue by dakshaau** [iit-cs429/main#145]
What is the base of the log for scoring of each document supposed to be?

using base 'e' I got 10 false spam docs, and accuracy of 0.985
using base 10 I got 9 false spam docs and an accuracy of 0.986

The output provided in Log.txt has accuracy of 0.987 with 8 false spam docs

Everything else in my output matches the provided output exactly.

**Comment by aronwc** [comment]
log10

**Comment by dakshaau** [comment]
When I am using math.log10, I am getting the output I mentioned above. Will that work?

**Comment by aronwc** [comment]
Your output should match the log.
