### ISSUE TITLE
a3 helper functions

### ISSUE THREAD

**Issue by mbaroody** [iit-cs429/main#146]
Can we define helper functions? And if so, should they be defined as part of the class definition for NB or outside the class definition?

**Comment by lwalsh2** [comment]
I would assume you could, since the tests normally test output. Leaving them within the class should make them easier to call.

**Comment by JamalK** [comment]
I actually submitted assignments before with helper functions and they were graded fine, so I assume it's okay. I mean basically helper function is just the same code just more organized so why not.

**Comment by aronwc** [comment]
Yes. Either way is fine, but they should be instance methods if they access
NB instance variables.
