### ISSUE TITLE
score of terms never seen before

### ISSUE THREAD

**Issue by cgarciahdez** [iit-cs429/main#147]
![image](https://cloud.githubusercontent.com/assets/10619844/14089343/140a411a-f4fa-11e5-826f-b34f00dc1f0b.png)

In this method, when the term t in the current document has never been seen before (it wasn't in the training documents) the condprob[t][c] will be zero, right? Which will break the code as log of zero is illegal. When this happens, should we just ignore this term and assume we don't add anything or should something else be done?

**Comment by aronwc** [comment]
You may ignore terms that appear in the test set but not in the training
set.
