### ISSUE TITLE
Classify Takes 3-5 minutes to run

### ISSUE THREAD

**Issue by jmwaks** [iit-cs429/main#148]
My code is giving the correct output but takes 3-5 minutes to go through all the documents. Is this expected?

**Comment by aronwc** [comment]
Please try to make it more efficient. Mine runs in ~2-3 seconds.
To help, you should only have to pass through the documents once during
training (to count all the token frequencies).
-Aron

**Comment by jmwaks** [comment]
Thanks. I will improve that.

**Comment by AyeshaAhmed** [comment]
Yes I had the same problem. Found 2 fixes:
1) I iterated over train documents twice
2) in train function I used spam_terms = **collections.Counter**(num_of_spams)
