### ISSUE TITLE
A3 : taking more time to complete

### ISSUE THREAD

**Issue by changediyasunny** [iit-cs429/main#149]
Code is taking 5-6 mins even after improvements. what else can be done ? any suggestions ?

**Comment by ywang315** [comment]
check for nested for-loops. 
I had problem with "do condprob[t][c] ← " earlier 
after I fixed the problem, it only takes a few seconds now

**Comment by changediyasunny** [comment]
Okay. I guess it is taking more time in "classify" only. let me try out this again.

**Comment by aronwc** [comment]
You can try a profiler to see what part of your code is slow. E.g:
http://jiffyclub.github.io/snakeviz/

**Comment by cgarciahdez** [comment]
It was happening to me because I calculated the sum in the denominator every time I iterated over a t in V. The sum of therms for every class can be calculated before the loop. Changed it and it's considerably faster.
