### ISSUE TITLE
A3: All ham, no spam

### ISSUE THREAD

**Issue by ProdigalTechnician** [iit-cs429/main#150]
In my train method, when I attempt to take in documents and do computations, before I can do so for spam it seems to detecting all documents as ham from their labels. I haven't messed with the Document class so I'm not sure why all labels are being treated as ham. Any ideas as to what might be causing this?

**Comment by ywang315** [comment]
Your spelling?

**Comment by ProdigalTechnician** [comment]
I don't think I've misspelled spam, would single vs double quotes make any
difference?

**Comment by ProdigalTechnician** [comment]
It worked. "spam" needed to be 'spam', although I'm not sure why since
"ham" had no issues.
