### ISSUE TITLE
A3: Word Probability Doctest

### ISSUE THREAD

**Issue by Brownie79** [iit-cs429/main#151]
For the following doctest in get_word_probability(), 
```python
>>> docs = [Document(label='spam', tokens=['a', 'b']), Document(label='spam', tokens=['b', 'c']), Document(label='ham', tokens=['c', 'd'])]
>>> nb = NaiveBayes()
>>> nb.train(docs)
>>> nb.get_word_probability('spam', 'a')
0.25
```
should the condprob['a']['spam'] not be:
(Tct + 1 ) / sumof( all Tct + 1)
Tct(a) = 1, Tct(b) = 2, Tct(c) = 1
so:
a / (a+b+c + 3)
(1+1) / (1+1  +  2+1  +  1+1)
= 2/7 ? (0.286)

But the doctest has 0.25 as the answer

**Comment by cgarciahdez** [comment]
That happens because in the denominator you need to take into account every term in te vocabulary, not only those terms belonging to the class, so you are missing d

**Comment by Brownie79** [comment]
Thanks! That worked!
