### ISSUE TITLE
Bonus Assignment: how to Initialize K mean vector to be first k-docs

### ISSUE THREAD

**Issue by changediyasunny** [iit-cs429/main#154]
Prof.,
1st step says: initialize K-mean vectors to be first K documents ? 
but we have each document as docs = [ Counter{'a':3, 'b':2, 'c':5}, Counter{....}, ...]
where docs[0] represent 1st document dictionary which has many "key - value" pairs.

So how to programmatically initialise it ?  Do we have to find mean of all "values" from  docs[0] and after getting single mean value represent it as a K-mean vector ? same for all K- documents?

After going through book, all is clear about algorithm, but how to do it programmatically? 
Could you explain it with above example as a reference ?

**Comment by pbhagav1** [comment]
Each document is represented as a "Counter" in the assignment and so the mean vectors will also be represented as "Counters" only. So for the given example, when initialized the first mean vector value is {Counter{'a':3, 'b':2, 'c':5} and second vector will be same as the second document (Counter) present in the list of docs and so on.

As we iterate, we update the mean vector feature values based on the feature values of all the documents that belong to the vector. Hope this clarifies.

Thanks,
Prasanth Bhagavatula

**Comment by dakshaau** [comment]
For initialization, we have to select K random documents as mean right?
And K-Means is sensitive to initialization, then will the output still be same for everyone?

**Comment by karthikbmk** [comment]
We will have to select the first K documents.

**Comment by aronwc** [comment]
Correct, the first k documents are used as the initial means.
