### ISSUE TITLE
Bonus Assignment: need of "mean_norm" in distance() method ?

### ISSUE THREAD

**Issue by changediyasunny** [iit-cs429/main#155]
It is said that we have to return euclidean distance between (doc, mean_vector). So do we really need that to calculate euclidean distance ?

I guess we can anyway calculate euclidean distance between doc & mean_vector without need of "mean_norm" . Am I missing something ?

**Comment by aronwc** [comment]
Yes, you should use mean_norm. Please follow the link in the comments:
http://en.wikipedia.org/wiki/Cosine_similarity#Properties

This lists an equivalent way to compute cosine similarity using the norms
of each vector A and B. By using this method, we can compute the mean norm
once and re-use it to compute the distances for all points.

-Aron

**Comment by skrzepto** [comment]
Im still confused how we use mean_norm to calculate euclidean distance?

Example

v1 = <1, 2, 3>
v2 = <4, 5, 6>

The euclidean distance is sqrt(27)

but if we use the the cosine sim its

2(1- (1/|v1|)(1/|v2|) * (v1 * v2)) which results in -0.08

how are we supposed to go back to un normalized value?

**Comment by skrzepto** [comment]
or do we use

||A||^2 + ||B||^2 -2A*B

**Comment by aronwc** [comment]
Yes, that is the valid formula. The `mean_norm` parameter is equivalent to ||B||^2. So, in the distance function, you compute the document norm (||A||^2) and -2A*B (two times the dot product of the document and the cluster mean). You'll finally have to take the square root of the result to get the distance.

**Comment by skrzepto** [comment]
Could you further optimize by storing the document norm in an instance?

**Comment by aronwc** [comment]
You could but no need to for this assignment.
Note that the documents typically have significantly fewer non-zero values than the means, so this is somewhat less of an issue.
