### ISSUE TITLE
Bonus: I'm off by a little in each iteration

### ISSUE THREAD

**Issue by skrzepto** [iit-cs429/main#157]
![selection_008](https://cloud.githubusercontent.com/assets/3166193/14479692/e16c7054-00e6-11e6-8ce3-e5922f7a62ea.png)

The above is the vim diff. Anyone have any pointers as too why I'm getting this output? I'm super close and wondering where I am off

**Comment by pbhagav1** [comment]
Its hard to tell just by looking at this output. The issue might be in the distance function itself or it might be only in the compute_clusters and error functions, which determine the values printed in the output.

Also, you might need to check print_top_docs too as the expected documents and the printed documents do not match.

**Comment by skrzepto** [comment]
part of the issue was distance since i was rounding in it thanks. Now i need to figure out print_top_docs and i should be good

**Comment by skrzepto** [comment]
Could someone post their distance for cluster 0 documents because I'm not sure how my cluster len and error is perfect but my documents printed in each cluster are off. Here's my output which is wrong

`
CLUSTER 0
a k twife	1.7786008520229146
a it marriage not s	2.1057834648534217
a d dm pin wa	2.253101078309073
a boy country dream ig just with	2.5365969330680196
a dream just making moves nigga young	2.593961908378954
a desire man simple w	2.817090030803552
a at difference make one step time to trying	2.8671025754422543
a mu se star student ti to wars z	2.9909914219985336
a freereggie girl just life living pretty	3.0529676752740347
a everyday fight have isn it playground s t to you	3.089448477289542
CLUSTER 1

`

**Comment by pbhagav1** [comment]
This is my Cluster 0 docs and scores.

CLUSTER 0
a of prince princess 1.8907120955541725
a it marriage not s 2.105783464853426
a always failure lesson never 2.2501303390373013
a always lesson mistake never 2.2501303390373013
a d dm pin wa 2.253101078309077
a am ap aries i ucdavis 2.2627290447481974
a queen s to what whore 2.3196577969960317
a destination journey life not s 2.329728533035426
a l potterhead s w y 2.3794429495186433
a and attitude heart smile tattoos with 2.469792671524269

Also, just wanted to highlight the "Note" mentioned in the 'print_top_docs' function. We need to consider documents with more than 3 distinct terms and I can see the first document has only 3 distinct terms.

**Comment by skrzepto** [comment]
Thank you very much my replacement function was replacing the first instance of a document that was greater than the next document instead of replacing the farthest document

**Comment by skrzepto** [comment]
Hmm it seems that two documents in Cluster 2 are swapped. could you post the distances as well 

Here's my results

CLUSTER 2
and art i like m	1.98655428656259
a am i m single	2.0059405061629203
different i m promise	2.0809370154458717
can i m say what	2.1847249988172663
i it like look	2.211486011549843
am i therefore tweet	2.2323865337899207
i l me per	2.232386533789921
a i it ll m misfit	2.2565258184593224
a am god i king m the	2.260638100352797
famous i was wish	2.3254458159797498


![selection_009](https://cloud.githubusercontent.com/assets/3166193/14507778/f2be2836-0189-11e6-9d57-501753cbae42.png)

**Comment by pbhagav1** [comment]
Actually I got difference for docs in two clusters. I mailed professor and he said that output is fine. Below is the vimdiff of my output. When I printed the distances, they were varying in the least significant decimal point.

![screenshot from 2016-04-13 15 17 14](https://cloud.githubusercontent.com/assets/16548617/14507961/d78379bc-018a-11e6-9630-5d7ef2ab2870.png)

**Comment by skrzepto** [comment]
Ah that makes sense. Thank you for clarifying.
