### ISSUE TITLE
Runitme for bonus assignment

### ISSUE THREAD

**Issue by dakshaau** [iit-cs429/main#158]
I am having a runtime of 693.0s

The output is correct, I have used numpy wherever possible. Any suggestions?

**Comment by pbhagav1** [comment]
You could probably check the below things.
1. Distance function optimization
2. In compute-clusters function, computing the 'sqnorm' of all mean vectors only once, which will be passed to the distance function.

**Comment by skrzepto** [comment]
Mines like 20s. Make sure you use the optimization for distance in the notes and try to store some of those variables

**Comment by dakshaau** [comment]
I am using the efficient version for euclidean calculation which someone asked in previous issues, using dot product of common features and sqnorms of mean and document.

To find common features I am using set intersection on the elements() of both Counters.

I recorded my timings for cluster and mean calculation, time taken is around 25 sec,
and for error calculation it is around 3 sec
