### ISSUE TITLE
PageRank: Issue with compute page rank

### ISSUE THREAD

**Issue by skrzepto** [iit-cs429/main#160]
I would like to clarify the formula provided

`    The formula is R(u) = (1/N)(1-b) + b * (sum_{w in B_u} R(w) / (|F_w|)`

Is B_u the inlinks of u 
and then |F_w| the outlinks length of the inllinks of u?

If so I was having a difficult time having 'b' pass because by hand I keep getting .416 but the doctests say .333.

My work below trying to do the the function by hand.

Ignore the green text in one of the pictures we were trying to reverse engineer the solution from the doctest.

![img_20160420_165731](https://cloud.githubusercontent.com/assets/3166193/14691986/e8ee6c40-0719-11e6-83df-413951c6502b.jpg)
![img_20160420_165151](https://cloud.githubusercontent.com/assets/3166193/14691987/e8f542d6-0719-11e6-8c50-d04baf275108.jpg)

Also is there a reason that some of the doctest inlinks/outlinks are lists and others are sets?

**Comment by pbhagav1** [comment]
I was coding and faced same issue. But, when we use the newly calculated Page Rank of 'a', while calculating the new Page Rank for 'b', I am getting 0.333. So, I am assuming that we need to use the new Page Rank value all the time.

**Comment by skrzepto** [comment]
It does work but for some reason I remember that we needed to use R_old to compute R_new from lecture

**Comment by pbhagav1** [comment]
I was just going through the slides in http://www.mmds.org/mmds/v2.1/ch05-linkanalysis1.pdf

On slide number 27 in the example given, for Iteration 1, while calculating the new page rank for 'm', the formula was mentioned as (pagerank of 'a / 2) and old page rank of 'a' is 1/3 and so the new page rank of 'm' calculated is 1/6.

Professor, 

Can you please clarify whether we need to use the old Page Rank or the new Page Rank?

**Comment by aronwc** [comment]
Please use the *new* Page Rank value in this computation to get results comparable to mine. (Both ways are technically valid, but we'll have to pick one for comparison purposes.)
