### ISSUE TITLE
Wrong Inlinks values from read_links method

### ISSUE THREAD

**Issue by dmallass** [iit-cs429/main#162]
I am getting below outlinks  values for each html file. Total outlinks number matches with expected output, but  outlink values from each file is one less than expected

read 509 people with a total of 5047 outlinks

When i compared my outlinks from each page against professors, I am getting one less outlink for each file . I corrected the  period missing at the end of 'Guy_L._Steele,_Jr' ; Below are my outlinks for %C3%89va_Tardos (16 outlinks)

 SortedSet(['Christos_Papadimitriou', 'G%C3%A1bor_Tardos', 'Johan_H%C3%A5stad', 'Joseph_Halpern', 'Madhu_Sudan', 'Manindra_Agrawal', 'Mario_Szegedy', 'Neeraj_Kayal', 'Rajeev_Motwani', 'Sanjeev_Arora', 'Seinosuke_Toda', 'Shafi_Goldwasser', 'Shang-Hua_Teng', 'Silvio_Micali', 'Steven_Rudich', 'Yoav_Freund'], key=None, load=1000)

Can someone tell me what's wrong here ?

**Comment by dakshaau** [comment]
17 outlinks is including "%C3%89va_Tardos". Are your page ranks matching
the output?

On Fri, Apr 22, 2016, 12:19 PM dmallass <notifications@github.com> wrote:

> I am getting below outlinks values for each html file. Total outlinks
> number matches with expected output, but outlink values from each file is
> one less than expected
>
> read 509 people with a total of 5047 outlinks
>
> When i compared my outlinks from each page against professors, I am
> getting one less outlink for each file . I corrected the period missing at
> the end of 'Guy_L._Steele,_Jr' ; Below are my outlinks for %C3%89va_Tardos
> (16 outlinks)
>
> SortedSet(['Christos_Papadimitriou', 'G%C3%A1bor_Tardos',
> 'Johan_H%C3%A5stad', 'Joseph_Halpern', 'Madhu_Sudan', 'Manindra_Agrawal',
> 'Mario_Szegedy', 'Neeraj_Kayal', 'Rajeev_Motwani', 'Sanjeev_Arora',
> 'Seinosuke_Toda', 'Shafi_Goldwasser', 'Shang-Hua_Teng', 'Silvio_Micali',
> 'Steven_Rudich', 'Yoav_Freund'], key=None, load=1000)
>
> Can someone tell me what's wrong here ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/iit-cs429/main/issues/162>
>
-- 

Daksh Gupta

Illinois Institute of Technology | Chicago, IL

Master of Science in Computer Science | 2017

Bachelor of Technology in Computer Science | 2015

dakshkumargupta@gmail.com | https://www.linkedin.com/in/dakshgupta

**Comment by dmallass** [comment]
I am getting different values for page rank. 
Top page ranks:
Donald_Knuth	0.01780
Rudy_Rucker	0.01708

I calculated the page rank with R_new . These are my inlink and outlink values for first two html pages 
Inlinks
'%C3%89va_Tardos', 18), ('Aaron_Sloman', 1),
outlinks
('%C3%89va_Tardos', 16), ('Aaron_Sloman', 3), 
Can you confirm if this is correct ?

**Comment by dakshaau** [comment]
Yes, this is correct.

On Sat, Apr 23, 2016, 2:27 AM dmallass <notifications@github.com> wrote:

> I am getting different values for page rank.
> Top page ranks:
> Donald_Knuth 0.01780
> Rudy_Rucker 0.01708
>
> I calculated the page rank with R_new . These are my inlink and outlink
> values for first two html pages
> Inlinks
> '%C3%89va_Tardos', 18), ('Aaron_Sloman', 1),
> outlinks
> ('%C3%89va_Tardos', 16), ('Aaron_Sloman', 3),
> Can you confirm if this is correct ?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/iit-cs429/main/issues/162#issuecomment-213681563>
>
-- 

Daksh Gupta

Illinois Institute of Technology | Chicago, IL

Master of Science in Computer Science | 2017

Bachelor of Technology in Computer Science | 2015

dakshkumargupta@gmail.com | https://www.linkedin.com/in/dakshgupta
