### ISSUE TITLE
HITS normalization

### ISSUE THREAD

**Issue by karthikbmk** [iit-cs429/main#163]
Prof,

Shouldn't we normalize the weights of hubs and authorities ? It's not summing to 1 below(highlighted in yellow):

![image](https://cloud.githubusercontent.com/assets/8171762/14846925/06c5212c-0c1b-11e6-9c8b-ea4620551a5e.png)

**Comment by aronwc** [comment]
The slides are normalizing by vector norm sqrt[ \sum_i x**2].
In the code sample I posted, I just normalized by the sum of values.
Either will work.
