### ISSUE TITLE
Off by 0.0004 & 12 links

### ISSUE THREAD

**Issue by spacemandev-git** [iit-cs429/main#166]
My log:
read 509 people with a total of 5035 inlinks
read 509 people with a total of 5035 outlinks
Top page ranks:
Donald_Knuth    0.08330
Rudy_Rucker 0.07950
Fred_Brooks 0.07437
Adi_Shamir  0.07034
Douglas_Engelbart   0.06995
Allen_Newell    0.06983
Stephen_Wolfram 0.06713
Alan_Kay    0.06580
Niklaus_Wirth   0.06455
Alan_Perlis 0.06413
E._Allen_Emerson    0.06372
Herbert_A._Simon    0.06280
Dennis_Ritchie  0.06268
Edmund_M._Clarke    0.06259
Amir_Pnueli 0.06208
Dana_Scott  0.06063
John_McCarthy_(computer_scientist)  0.05962
John_Cocke  0.05947
Barbara_Liskov  0.05920
Charles_Bachman 0.05895

This is _extremely_ close to the actual log file, but off by 12 links and just _slightly_ off for each value. Anyone else run into this issue ? Any advice on how to debug this?

**Comment by dakshaau** [comment]
Your '5035' figure seems similar to what I got nefore fixing an issue. There is a filename name with a  Guy Steele "Jr" in the end of it, that filename should end with "Jr."

**Comment by spacemandev-git** [comment]
Yea! So turns out my code is actually correct and works as intended on my linux computer. Windows is just buggy because of that guy's name. Won't let me add the '.' Thanks for the heads up!

I am curious as to how you actually figured out that was the error though? Seems like a needle in an impossibly large haystack to figure out

**Comment by dakshaau** [comment]
I posted this issue earlier, Prof. posted some reference files at that time which helped me figure this out.

[https://github.com/iit-cs429/main/issues/159](url)

**Comment by spacemandev-git** [comment]
ah yes, If I had sample outlinks file, I suppose it'd be signifcantly easier to debug.

Thanks for the help!
