### ISSUE TITLE
how to copy files to my private repository

### ISSUE THREAD

**Issue by ravitejachebrolu** [iit-cs429/main#20]
how do i copy those files from main to my repository??

**Comment by aronwc** [comment]
1- clone your private repo to your computer: e.g., `git clone https://github.com/iit-cs429/ravitejachebrolu-asg`
2- clone the main repo: `git clone https://github.com/iit-cs429/main.git`
3- copy files from main to your private repo: `cp main/assignments/assignment0/* ravitejachebrolu-asg/a0/`

You'll then complete your assignment, then do:
```sh
git add ravitejachebrolu-asg/a0/*
git commit -m 'submit assignment0'
git push 
```

**Comment by ravitejachebrolu** [comment]
thankyou sir :)
