### ISSUE TITLE
Private repo 404?

### ISSUE THREAD

**Issue by morerunes** [iit-cs429/main#21]
I don't think my private repo was created, is there a way for me to double-check?

**Comment by aronwc** [comment]
An invite from github should have been sent to whichever email address you
used for GitHub. Once you accept that invite, you'll be added to the
morerunes team, which is a collaborator on the repo
https://github.com/iit-cs429/morerunes-asg .

-Aron

**Comment by morerunes** [comment]
Got it, thanks!
