### ISSUE TITLE
setup problem with git

### ISSUE THREAD

**Issue by sjain41** [iit-cs429/main#22]
i am trying to setup git by following the instructions given but it gives me error when i am typing 
git config --global sjain41 "Smit Jain"
error:key does not contain selection:sjain41
Please help.
![capture2](https://cloud.githubusercontent.com/assets/10426532/5812952/7381667a-a03a-11e4-84a1-e0ec62653c80.JPG)

**Comment by ryanellison** [comment]
You need to do something more like:
git config --global user.name "Smit Jain"
And, use user.email to set your email address.
