### ISSUE TITLE
No tests run for doctest

### ISSUE THREAD

**Issue by dbajic** [iit-cs429/main#24]
So as I mentioned in class, I had the issue where when I ran the doctests, no tests ran:

    $ python -m doctest boolean_search.py -v
    8 items had no tests:
       boolean_search
       boolean_search.create_index
       boolean_search.intersect
       boolean_search.main
       boolean_search.read_lines
       boolean_search.search
       boolean_search.sort_by_num_postings
       boolean_search.tokenize
    0 tests in 8 items.
    0 passed and 0 failed.
    Test passed.

However running the code normally produces the expected results. I doubt it's a path issue since the doctest actually ran, so I'm not sure what the issue could be.

**Comment by JaySurplus** [comment]
Hey,
I have looked at your code. You should place 'doctest' part in front of your code.
eg.

def create_index(tokens): 
    """
    Create an inverted index given a list of document tokens. The index maps
    each unique word to a list of document ids, sorted in increasing order.
    >>> index = create_index([['a', 'b'], ['a', 'c']])
    >>> sorted(index.keys())
    ['a', 'b', 'c']
    >>> index['a']
    [0, 1]
    >>> index['b']
    [0]
    >>> index['c']
    [1]
    """
    d = dict([])
    i = 0
    for docs in tokens:
        for t in docs:
            if (t not in d.keys()):
                d[t] = [i]
            elif (t in d.keys()) and (i not in d[t]):
                d[t].append(i)
        i+=1
    return d

**Comment by dbajic** [comment]
That would do the trick, thank you very much!
