### ISSUE TITLE
Tokenize function

### ISSUE THREAD

**Issue by bpraveen92** [iit-cs429/main#25]
hi, the tokenize function should be built to split each sentence into individual lists within the parent list or is it supposed to split the sentences according to the given sample test case under the tokenize function (i.e) splitting all sentences into one single list ??

**Comment by JaySurplus** [comment]
You can view each line as a sentence then each should be contain in an individual list.

**Comment by JaySurplus** [comment]
Split whatever that passed in the function and store them in a list. If you call tokenize function K times , then there should be K list.

**Comment by bpraveen92** [comment]
If we do it this way as in splitting on each sentence to form individual list then my function fails the sample test case. My output is like this [['hi', 'there', 'what', 's', 'going', 'on']] for the sample case..

**Comment by benjaminwalters** [comment]
You need to return just a list of strings. You seem to be returning a list (outer brackets) with a single item that is a list of strings (inner brackets). You don't want that outer list.

**Comment by JaySurplus** [comment]
The thing passed into the function should be a String , not a list.

```python
    tokenize("Hi there. What's going on????")
```

**Comment by aronwc** [comment]
@bpraveen92 please close this issue if it has been resolved. Otherwise, feel free to ask additional questions.
-Aron

**Comment by JaySurplus** [comment]
@bpraveen92 This ticket will be closed.

**Comment by bpraveen92** [comment]
I'm sorry to reply late..I still have one more doubt, If thats the case then under the create_index function the professor has passed a list with sublists as argument #24 create_index([['a', 'b'], ['a', 'c']])
that obviously means that he's trying to pass multiple sublists within a parent list as a paramenter ..am i right ??
