### ISSUE TITLE
Tokenize function -contd

### ISSUE THREAD

**Issue by bpraveen92** [iit-cs429/main#26]
I'm sorry to reply late..I still have one more doubt, If thats the case then under the create_index function the professor has passed a list with sublists as argument create_index([['a', 'b'], ['a', 'c']])
that obviously means that he's trying to pass multiple sublists within a parent list as a paramenter ..am i right ??

**Comment by JaySurplus** [comment]
Yes. 
```python
   create_index([['a', 'b'], ['a', 'c']]) 
```
It takes a `list` as input, each elements in that list is still a `list`.

**Comment by bpraveen92** [comment]
yes so how would you pass the argument for the example below:
>>tokenize("Hi there. What's going on?")
    ['hi', 'there', 'what', 's', 'going', 'on'] --> tokens
u pass these tokens to the create_index function like create_index( ['hi', 'there', 'what', 's', 'going', 'on']) ??
Where do u find two lists here ? Its just a single list right ?
According to what you say then you are supposed to pass the parameter as create_index( [['hi', 'there', 'what', 's', 'going', 'on']]) ??

**Comment by JaySurplus** [comment]
You should pass [['hi', 'there', 'what', 's', 'going', 'on'],.....]
The structure is:`One parent list` contains `N child lists` , N >= 0.

**Comment by JaySurplus** [comment]
@bpraveen92  Please close this ticket if the issue has been resolved.

**Comment by bpraveen92** [comment]
ok thanks.
