### ISSUE TITLE
assignment0 file not read

### ISSUE THREAD

**Issue by sjain41** [iit-cs429/main#27]
i am running the code in ipython notebook, i cant happen to save documents.txt file. how can i save it there so i can run the code and have the code read the documents.txt file? currently it shows this error obviously:
IOError: [Errno 2] No such file or directory: 'documents.txt'

please help

**Comment by JaySurplus** [comment]
You need to set the path to `documents.txt` file when try to open or read it. 
eg. If the file is in the directory with ipython notebook, then you should run 
```python
open('./documents.txt')  # or similar operations here.
```

You can check detailed instructions at [here](http://nbviewer.ipython.org/github/herrfz/dataanalysis/blob/master/week2/getting_data.ipynb).

**Comment by sjain41** [comment]
in the main method the code is trying to access 'documents.txt', but in the code it says not to edit the code under main method. Should i still edit it there?

**Comment by aronwc** [comment]
The main method assumes you're not using an iPython notebook.

I recommend not using a notebook for this assignment.

**Comment by sjain41** [comment]
please recommend the best way where can i do the assignment? i would do that

**Comment by aronwc** [comment]
- Copy over all the assignment files as instructed here: https://github.com/iit-cs429/main/issues/20
- Edit boolean_search.py directly.
- You can then run the script calling `python boolean_search.py` from the command line (as instructed in the assignment).

**Comment by JaySurplus** [comment]
@sjain41 Professor recommend you to add your code in ` boolean_search.py` file. 
In terminal/cmd , use the following command to run/test your program.
`$ python  boolean_search.py`  or `python -m doctest boolean_search.py -v`

**Comment by sjain41** [comment]
i am getting problems when i am trying to clone using the command, so i cloned using clone button in github app on my computer directly. it does copy the files to my private repo but i am unable to edit the boolean_search.py file or any file for that matter

**Comment by aronwc** [comment]
The .py files are just text files. You can edit them with any text editor
or use a fancy IDE like: http://www.jetbrains.com/pycharm/
-Aron

**Comment by JaySurplus** [comment]
@sjain41 Please this ticket if the issue has been resolved.

**Comment by sjain41** [comment]
thanks i will try the suggestion
