### ISSUE TITLE
regarding skip lists

### ISSUE THREAD

**Issue by sjain41** [iit-cs429/main#29]
for short answer question 1 part a. does it mean how many elements are being skipped? I am not sure what how often is skip pointer "followed" means? please help!!

**Comment by JaySurplus** [comment]
It means list all the possible 'skip' when it happens. 
eg.  First: from a to b. 
       Second: from c to d.

**Comment by JaySurplus** [comment]
@sjain41  Please close this ticket once it has been resolved.
