### ISSUE TITLE
Assingment 1 Stemming Function

### ISSUE THREAD

**Issue by abarbosa94** [iit-cs429/main#30]
Hi ! For the Assignment 1, can we use the WordNet Lemmatizer to build the stem(tokens) function?

Thanks !

**Comment by rkalyan1** [comment]
Even I have the same question. Can we use the predefined stemmer or do we need to implement our own?

**Comment by vivekpabani** [comment]
For this assignment, it seems that the requirement is to just stem 'does' and 'did' to 'do'. It won't require any complex implementation.

**Comment by JaySurplus** [comment]
Use the simple way.
@rkalyan Just use the predefined.

**Comment by abarbosa94** [comment]
Thanks for the anwsers ! (:

Oh, so just to check: I only need to worry about "does" and "did"? Is it not necessary to handle with other words?

**Comment by aronwc** [comment]
correct.

**Comment by JaySurplus** [comment]
Issue resolved. Close ticket.
