### ISSUE TITLE
phrase_intersect

### ISSUE THREAD

**Issue by ryanellison** [iit-cs429/main#31]
There is not a test case provided for this, but if a phrase were to occur multiple times in the same document, should those results returned in one sub-list? For example, if a phrase occurred twice in document 0 and once in document 5, should it look something like
[[0, 3, 9], [5, 4]]
or should it be
[[0, 3], [0, 9], [5, 4]]
or, does it not matter for the purposes of this assignment...?

**Comment by JaySurplus** [comment]
It should be `[[0, 3], [0, 9], [5, 4]]`.

**Comment by vivekpabani** [comment]
Is it ok if we skip further search if we find the phrase once in the doc? In this example, is it ok if we return [[0, 3], [5, 4]]?

**Comment by JaySurplus** [comment]
For this assignment,please go through entire doc.

**Comment by vivekpabani** [comment]
So, we'll go through the entire doc, but will print it only once, right?

**Comment by JaySurplus** [comment]
Go through the entire doc and print all possible results.

**Comment by JaySurplus** [comment]
@ryanellison Please close this ticket if issue has been resolved.

**Comment by ryanellison** [comment]
Thanks!
