### ISSUE TITLE
Submission date for Assignment 1

### ISSUE THREAD

**Issue by TejashreeHinge** [iit-cs429/main#32]
Hi,
I want to confirm the submission date for Assignment 1.
In iit-cs429/main/assignments/assignment1, it is mentioned as 2/06 at 11:59pm but in schedule it is 2/05.
Could you please confirm the date.

**Comment by dougcirqueira** [comment]
It is 02/05, before class.

**Comment by aronwc** [comment]
It should be 2/05, but since I had it listed as 2/6 (and wasn't here last week), I will move the date to 2/6 at 11:59pm.
-Aron
