### ISSUE TITLE
Assingment 1 - Short Answers

### ISSUE THREAD

**Issue by abarbosa94** [iit-cs429/main#33]
Hi !

For the first question on the Short Answers part, should we provide the answers using asymptotic complexity or is it just necessary to iterate through the algorithm provided by the book  ("intersect with skips") ? (e.g. "the skip pointer is followed three times" for the first question).

Thanks !

**Comment by JaySurplus** [comment]
Please iterate through the algorithm, point out when the 'skip' will happen.
