### ISSUE TITLE
lemmatizing

### ISSUE THREAD

**Issue by sjain41** [iit-cs429/main#34]
even after downloading nltk its showing me to download, how to fix this error.
here is the link below ipython notebook as an example. please help
http://localhost:8888/notebooks/Untitled0.ipynb
![image](https://cloud.githubusercontent.com/assets/10426532/6046406/89409722-ac67-11e4-8e31-ea91a5e42d04.png)
![image](https://cloud.githubusercontent.com/assets/10426532/6046400/7883cada-ac67-11e4-84ef-d08f7f91198d.png)

**Comment by JaySurplus** [comment]
I believe it is due to a path issue. Please try to unzip the downloaded file to one of those directories:
    C:\\User\\Smit/nltk_data  etc....
For more detail , please check here : [http://web.mit.edu/course/6/6.863/devel2007/web/install_windows.html](http://web.mit.edu/course/6/6.863/devel2007/web/install_windows.html)
