### ISSUE TITLE
append 2 lists/dictionaries

### ISSUE THREAD

**Issue by FilipeTabosa** [iit-cs429/main#36]
Is it possible to append two lists or dictionaries? I was trying to do the create_positional_index code part and when I was looking at the expected results I saw this:

 >>> index['a']
    [[0, 0, 2], [1, 0]]
    >>> index['b']
    [[0, 1]]
    >>> index[('c')]
    [[1, 1]]

There are two brackets onthe beginning and end of each result, and when it comes to index of A, there are 2 lists, so to do so I would need to merge/append two dictionaries or lists in my index, but how can I do that?

**Comment by dougcirqueira** [comment]
Your dictionary will be a map from the term to a list of lists. For
instance, you just need to assign to 'a' in your dict the result [[0, 0,
2], [1, 0]].

**Comment by FilipeTabosa** [comment]
That wasn't exactly what I was looking for, but it did help me and I was able to finish this part of the code, thank you very much.
