### ISSUE TITLE
git pull not working

### ISSUE THREAD

**Issue by jhui216** [iit-cs429/main#37]
do I have to create the a1 folder?
I thought doing a git pull should copy the files for assignment 1 for me.

**Comment by jhui216** [comment]
![cs429_gitpull](https://cloud.githubusercontent.com/assets/10521767/6054127/d0db2e02-acae-11e4-8cd1-9418907e3e18.JPG)

**Comment by aronwc** [comment]
As in a0, please copy the files from the main/assignments/assignment1 folder to a new folder in your private repository (e.g., jhui216/a1)

**Comment by jhui216** [comment]
okay thanks.
