### ISSUE TITLE
How to delete a specific numbers on a dictionary?

### ISSUE THREAD

**Issue by FilipeTabosa** [iit-cs429/main#38]
Hey guys, I am having a bit of trouble in the last part of the top bigrams function. I was able to store the information of each bigrams in a dictionary and order the number in a decrescent order, so if we use the example that the professor gave in the code, the result would be "[('b c', 3), ('a b', 2), ('c a', 1), ('c d', 1)]". My question is, how can I eliminate some of the elements from the dictionary, but not all. For example, if the user type he wants just the top 3, I would eliminate just the last element of the dict, resulting in  "[('b c', 3), ('a b', 2), ('c a', 1)]."

**Comment by dougcirqueira** [comment]
You can just filter the elements of your result list and return it.

I hope it will help!

On Feb 6, 2015 12:48 PM, "FilipeTabosa" <notifications@github.com> wrote:
>
> Hey guys, I am having a bit of trouble in the last part of the top
bigrams function. I was able to store the information of each bigrams in a
dictionary and order the number in a decrescent order, so if we use the
example that the professor gave in the code, the result would be "[('b c',
3), ('a b', 2), ('c a', 1), ('c d', 1)]". My question is, how can I
eliminate some of the elements from the dictionary, but not all. For
example, if the user type he wants just the top 3, I would eliminate just
the last element of the dict, resulting in "[('b c', 3), ('a b', 2), ('c
a', 1)]."

**Comment by FilipeTabosa** [comment]
Yeah I was trying to do that, I just did not know how exactly to filter it as I do not know much about python, but I figured it out. Thank you for your help.
