### ISSUE TITLE
lemmatizer in stem function

### ISSUE THREAD

**Issue by sjain41** [iit-cs429/main#39]
i am getting 'u' before the word, i cant happen to find the reason. i cant get rid of it, please help
![image](https://cloud.githubusercontent.com/assets/10426532/6089299/5358baca-ae26-11e4-92a5-4da5076c59fa.png)

**Comment by vivekpabani** [comment]
You can use - encode('utf-8'). For example any string str1 = u'do', if you use str1.encode('utf-8'), it will give you just 'do'. Try to use this with your stem function.

**Comment by sjain41** [comment]
list object are not string, how can i convert it to string, so i can use what you suggested? thanks for the response.

**Comment by gchoi5** [comment]
lemm = WordNetLemmatizer()
return [term.encode('utf-8') for term in [lemm.lemmatize(token, 'v') for token in tokens]]

**Comment by vivekpabani** [comment]
Or just :
return [lemm.lemmatize(token, 'v').encode('utf-8') for token in tokens]

**Comment by sjain41** [comment]
oh wow.. awesome that works..thanks @vivekpabani  and @gchoi5
