### ISSUE TITLE
Issue with reading documents.txt

### ISSUE THREAD

**Issue by dbajic** [iit-cs429/main#40]
While I was trying to test things in my code, I received the following error trying to read the file:

    ValueError: Invalid mode ('rtb')

Looking a little bit deeper, the issue stems from these lines in codecs.py:

    876             # Force opening of the file in binary mode
    877             mode = mode + 'b'
    --> 878     file = __builtin__.open(filename, mode, buffering)

What exactly am I supposed to do in this case? I haven't modified any pre-given function.

**Comment by dougcirqueira** [comment]
Probably, you'd typed "t", while the mode is supposed to be, maybe " r+b".

**Comment by dbajic** [comment]
Problem with that is that 'rt' is already given to us in the assignment, so I can't change that.

**Comment by aronwc** [comment]
You may change to 'r' if that fixes your problem.

**Comment by dbajic** [comment]
That works, thanks!
