### ISSUE TITLE
compute_doc_length

### ISSUE THREAD

**Issue by sjain41** [iit-cs429/main#43]
lengths = Index().compute_doc_lengths({'a': [[0, 3]], 'b': [[0, 4]]})
how can i access docid '0' for both 'a' and 'b' and compare them if they r equal? I have spent so much time trying to do it but no result. how can i access the weight (which i think i can figure once i can access doc id)? Please Help!!

**Comment by benjaminwalters** [comment]
In this case the argument ``` index ``` would be ``` {'a': [[0, 3]], 'b': [[0, 4]]} ```. 

So ```index.items()``` returns a list of all (key, value) tuples: ```[('a', [[0, 3]]), ('b', [[0, 4]])]```. 
And ```index.values()``` returns a list of all values: ```[[[0, 3]], [[0, 4]]]```

You can then iterate through these lists and access the values you need. I hope that answers the question.

**Comment by JaySurplus** [comment]
To computer the length of a Document ,  you need to collect all the `Terms` in that Document.
You should  use some structures  to organize `DocID : [words in DocID]`

**Comment by sjain41** [comment]
@benjaminwalters i did try that before its not working, says 'nonetype' object has no attribute 'items'
@JaySurplus what type of organization would be needed? Please help. Is there any office hours tomorrow to meet with you? Thanks

**Comment by aronwc** [comment]
@sjain41 
Based on the code you've checked into your private repo, the 'nonetype' error is not coming from compute_doc_lengths; instead, it is coming from other tests. This is the error message you should focus on:

```
File "searcher.py", line 46, in searcher.Index.compute_doc_lengths
Failed example:
    lengths = Index().compute_doc_lengths({'a': [[0, 3]], 'b': [[0, 4]]})
Exception raised:
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest searcher.Index.compute_doc_lengths[0]>", line 1, in <module>
        lengths = Index().compute_doc_lengths({'a': [[0, 3]], 'b': [[0, 4]]})
      File "searcher.py", line 54, in compute_doc_lengths
        if j[0] in i[0] == j[0] in i[1]:
    IndexError: string index out of range
```

**Comment by sjain41** [comment]
i realized that few min ago and now i am rewriting the entire function using defaultdict()

**Comment by sjain41** [comment]
from my understanding index already has the sample example(below) stored in it. Index().compute_doc_lengths({'a': [[0, 3]], 'b': [[0, 4]]})
Then, why still the same error of  'nonetype' object has no attribute 'values'
its showing at this line : for iter in index.values():
please help!! Thank you

**Comment by aronwc** [comment]
@sjain41 
When debugging, I recommend looking at the very first error message when you run `python -m doctest searcher.py`. For your currently checked in code, this is:

```
File "searcher.py", line 46, in searcher.Index.compute_doc_lengths
Failed example:
    lengths = Index().compute_doc_lengths({'a': [[0, 3]], 'b': [[0, 4]]})
Exception raised:
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest searcher.Index.compute_doc_lengths[0]>", line 1, in <module>
        lengths = Index().compute_doc_lengths({'a': [[0, 3]], 'b': [[0, 4]]})
      File "searcher.py", line 55, in compute_doc_lengths
        for i,l in templist:
    ValueError: need more than 1 value to unpack
```
Prior to your for loop `for i,l in templist`, `templist` is assigned the result of `index.values()`, which is a list of lists. So, `templist[0]` is the postings list for the first term ('a'). 

Perhaps you mean `for sublist in templist` ? Then, you can refer to the tf-idf value as `templist[1]`

**Comment by sjain41** [comment]
templist[1] is showing me indexerror: list index out of range.  i am not sure where my logic is incorrect. please help

**Comment by aronwc** [comment]
```
>>> # Here is the index
... index = {'a': [[0, 3]], 'b': [[0, 4]]}
>>> # index.values() is the list of postings lists
... index.values()
[[[0, 3]], [[0, 4]]]
>>> # Let's get the first postings list.
... plist = index.values()[0]
>>> plist
[[0, 3]]
>>> # In your code, you create an empty list called templist.
... templist = []
>>> # Then you add the first element of index.values() to it.
... templist.append(plist)
>>> templist
[[[0, 3]]]
>>> # Then, in your for loop, you try to iterate over templist[1], which does not exist (it only has length 1)
... for i, l in templist[1]:
...   print i
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
IndexError: list index out of range
>>> # Instead, I think you mean to iterate over the postingslist.
>>> for i, l in templist[0]:
...   print i, l
... 
0 3
>>> 
```

**Comment by sjain41** [comment]
thanks a lot that helped.
