### ISSUE TITLE
query_to_vector

### ISSUE THREAD

**Issue by saiarjuntanguturi** [iit-cs429/main#44]
Hi,

Can you give me an example for query_to_vector ? I'm a little confused by the input, as well as the output you're asking for. Could you give me a sample input and sample output? I'm confused by whether we are given a list of lists where each sublist represents one document, or if we are given one list with multiple words in it. 

Thanks!

**Comment by dougcirqueira** [comment]
Hi,
Input: ["cat", "dog"]
Output: {"cat":0.2, "dog": 0.7}

Remember that the class Index has the variables documents and doc_freqs,
which can help in the computation.

Hi,

Can you give me an example for query_to_vector ? I'm a little confused by
the input, as well as the output you're asking for. Could you give me a
sample input and sample output? I'm confused by whether we are given a list
of lists where each sublist represents one document, or if we are given one
list with multiple words in it.

Thanks!

—
Reply to this email directly or view it on GitHub
<https://github.com/iit-cs429/main/issues/44>.

**Comment by saiarjuntanguturi** [comment]
Awesome. Thanks!
