### ISSUE TITLE
Output of assignment 2 not matching

### ISSUE THREAD

**Issue by gulavanir** [iit-cs429/main#45]
I am getting slightly different values (change in decimal point) for document score, therefore the output of my code is not matching with the output given, sometimes even the top 10 document ids are changing.
For e.g my output of QUERY= pop love song
4330    1.619429e+00
2203    9.325103e-01
2205    8.227300e-01
4693    7.713332e-01
312      6.915496e-01
5113    6.480366e-01
3401    6.463378e-01
4996    6.095998e-01
2683    5.734033e-01
2162    5.492592e-01

Is it acceptable? or is there any workaround?

**Comment by vivekpabani** [comment]
Check the places where you are using math.log10 . Provide the arguments in float. for example - math.log10(float(x)/float(y)). This may help.

**Comment by gulavanir** [comment]
Tried that, the values are changing at 3rd or 4th decimal point so no change in the output.

**Comment by aronwc** [comment]
@gulavanir 
Please double check (there are a couple places where integer division could be happening).

Also, please checkin your latest code.

**Comment by aronwc** [comment]
One way to debug (which will admittedly take some effort) is to start with a very small collection, say 3 documents, and compute the values by hand. Then, compare with each step of your code.

**Comment by gulavanir** [comment]
I have checked in the latest code. I converted every division to float still getting the same result.

**Comment by aronwc** [comment]
It appears there is an error in your `compute_doc_lengths`. Please try a few more test cases.

**Comment by gulavanir** [comment]
Got the issue. Working now. Thank you.
