### ISSUE TITLE
Output 

### ISSUE THREAD

**Issue by pcastrotigre** [iit-cs429/main#47]
Do we need exactly the same out of Log.txt? I have this.

QUERY= city Using Champion List
1199	2.679080e-01
3691	2.367081e-01
2680	1.913987e-01
410	        1.750654e-01
4256	1.516835e-01
3288	1.516195e-01
811	        1.490004e-01
1983	1.416778e-01
2336	1.241685e-01
5362	9.983552e-02

However the Log.txt has this:
QUERY= city Using Champion List
1199	2.674604e-01
3691	2.366818e-01
2680	1.912368e-01
410	        1.749006e-01
4256	1.516393e-01
3288	1.516023e-01
811	        1.489597e-01
1983	1.415582e-01
2336	1.241447e-01
5362	9.984798e-02

Similar cases for all the queries

**Comment by dougcirqueira** [comment]
The values may change accordingly to the way you do the computation, as well as the float precision of your computer. I believe, if the order of rank is the same and values are close, it does not matter.

**Comment by JaySurplus** [comment]
What about other outputs ? Are they exactly the same or still with minor differences in the values ?

**Comment by dbajic** [comment]
If you're having minor differences in values, it's most likely because of how Python 2.x handles division. For example:
```
    >>>print math.log10(3/2)
    0.0
```
is not the same as:
```
    print math.log10(3.0/2.0)
    0.176091259053
```
This is because the division of 3/2 in Python is integer division, so 3/2 would return 1, hence log(1) = 0. log(3/2) is clearly not 0. Check for this in your code.

**Comment by pcastrotigre** [comment]
Awesome... It works now... Thanks @dbajic
