### ISSUE TITLE
doc frequency

### ISSUE THREAD

**Issue by sjain41** [iit-cs429/main#49]
i am unable to find the doc frequency, rather i end up finding the number of terms in total. Please Help. Any tips on how to proceed. and for professor i have my recent code checked in.
Thank you

**Comment by dougcirqueira** [comment]
When you are counting the terms, try to save when you've seen one of them.
This way, you will not count repeated ones. Something like.

In addition, python has a built-in function to count occurrences of an item
in a list: list.count(*x*)

On Wed, Feb 18, 2015 at 4:40 PM, sjain41 <notifications@github.com> wrote:

> i am unable to find the doc frequency, rather i end up finding the number
> of terms in total. Please Help. Any tips on how to proceed. and for
> professor i have my recent code checked in.
> Thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iit-cs429/main/issues/49>.
>



-- 




*Sincerely,Douglas R. Cirqueira*

*+55 91 80322716*

*Skype: douglas.cirqueira*



*Computer Engineering Student - Illinois Institute of Technology
<http://web.iit.edu/>Federal University of Pará - ENGCOMP/UFPA*

**Comment by JaySurplus** [comment]
First , Convert each doc from `list` to `set()`. In python , set() only store the unique terms.
Then iterate the sets and count number.

**Comment by sjain41** [comment]
thanks a lot for your comments. will try to implement based on what both of you said.

**Comment by dougcirqueira** [comment]
Nice approach @JaySurplus !

On Wed, Feb 18, 2015 at 4:53 PM, sjain41 <notifications@github.com> wrote:

> thanks a lot for your comments. will try to implement based on what both
> of you said.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iit-cs429/main/issues/49#issuecomment-74966103>.
>



-- 




*Sincerely,Douglas R. Cirqueira*

*+55 91 80322716*

*Skype: douglas.cirqueira*



*Computer Engineering Student - Illinois Institute of Technology
<http://web.iit.edu/>Federal University of Pará - ENGCOMP/UFPA*
