### ISSUE TITLE
Short Answer #2

### ISSUE THREAD

**Issue by saiarjuntanguturi** [iit-cs429/main#53]
For this short answer: 
Consider the query chinese with and without using champion lists. Why is the top result without champion lists absent from the list that uses champion lists? How can you alter the algorithm to fix this?

You mean the query 'Chinese american' given in Log.txt  right? Not just Chinese

**Comment by aronwc** [comment]
No, I meant "Chinese", although the same problem may appear for "Chinese
American"
-Aron

On Thu, Feb 19, 2015 at 1:22 PM, saiarjuntanguturi <notifications@github.com
