### ISSUE TITLE
Assignment3: query regarding top 20 results

### ISSUE THREAD

**Issue by gulavanir** [iit-cs429/main#56]
Assignment 3 mentions that we need to consider top 20 results while calculating all values. 
In case of cosine similarity this means that first cosine similarity for all the 83 queries with all the documents will be found out and then top 20 results will be returned. So the top 20 results will have docids returned for different queries. Is my understanding correct?  Or do we have to consider top 20 results for each query?

**Comment by aronwc** [comment]
For each query, return the top 20 results.

**Comment by gulavanir** [comment]
So the table in results.md will be calculated for all 83 queries right?

**Comment by aronwc** [comment]
Yes. There should be one table containing the average over 83 queries.

**Comment by gulavanir** [comment]
Thank you
