### ISSUE TITLE
Assignment3 TIME.REL

### ISSUE THREAD

**Issue by canichet** [iit-cs429/main#58]
I have two questions.
Q1.Should the relevant documents retrieved for each query match the exact order of the relevant documents listed in TIME.REL for each query ? 

Q2. For the second query the relevant documents are 326 334. If sorted by decreasing order of BM25 values for each docID should the documents 326 and 334 be the two top results ? or is it enough if these two documents(326,334) appear in the 20 results for the query ?

**Comment by aronwc** [comment]
Q1. No, the order in TIME.REL is insignificant. All listed documents are relevant to the query.

Q2. The optimal search engine would put 326/334 in position 1/2 (in either order). It is unlikely your search engine will do this.

**Comment by canichet** [comment]
Thank you Professor.
