### ISSUE TITLE
accessing time files

### ISSUE THREAD

**Issue by sjain41** [iit-cs429/main#59]
how can we access the time file, please give an example

**Comment by aronwc** [comment]
Can you clarify your question?
The time files are linked from the assignment:
http://ir.dcs.gla.ac.uk/resources/test_collections/time/

Download time.tar.gz and unzip into a folder called time/

**Comment by sjain41** [comment]
i meant how to access the time.que or time.all type files in the code to do all the calculations? i need help with that.

**Comment by JaySurplus** [comment]
You can just treat them as 'documents.txt' in assignment2 . Read the file line by line.

eg. in TIME.QUE  , each sentence has been separated into several lines.   You should combine them into one sentence.     Once read a line starts with `*FIND #(some number)`,  it means next several lines would be a new sentence.

**Comment by JaySurplus** [comment]
I am reviewing your code,  it will take some time to fix bug.  When do you want it ?
Regards,

Junzhe Zheng
IIT College of Science and Letters, Department of Computer Science
IIT College of Science and Letters, Department of Physics

**Comment by sjain41** [comment]
I am using assignment 2 code based on professors solution and also i tried to access the files the way its done in assignment 2, but its not working. It says "time.que" file not found. Whats the issue here?

Smit JAIn

**Comment by aronwc** [comment]
You will need to write new code to parse these files.

Make sure the file is in the proper place and capitalized correctly, e.g. "time/TIME.QUE"

**Comment by sjain41** [comment]
@JaySurplus as i was trying to get each queries(for each *FIND* stmt) in one line, i ended up getting all queries i.e. all FIND stmt in one line, is there any function that can limit it to print one query per line by comparing to each FIND? i have added latest code to repo
