### ISSUE TITLE
Assignment #3 query 4

### ISSUE THREAD

**Issue by canichet** [iit-cs429/main#60]
Professor,

for Query 4 in TIME.QUE which is
"U.S . POLICY TOWARD THE NEW REGIME IN SOUTH VIET NAM WHICH OVERTHREW PRESIDENT DIEM"
the relevant documents are 370 , 378 , 385 , 409 , 421 of which only 370 is relevant and rest are not.
for Example:
the Document 421 in the collection only contains the words 'u' , 's' , 'the' and 'in' . 
Document 421 is document "*TEXT 561" in TIME.ALL.

Can you please clarify ?

**Comment by aronwc** [comment]
It's possible some of the data was annotated incorrectly. Please proceed as usual.

> the Document 421 in the collection only contains the words 'u' , 's' , 'the' and 'in' .

I assume you mean those are the only matching terms. The document certainly contains other terms.
