### ISSUE TITLE
Assignment 3: Step 2 - Compare the following...

### ISSUE THREAD

**Issue by dougcirqueira** [iit-cs429/main#62]
What do we need to give in this part of the assignment? I have my top 20 results for each query, for all the systems. So, do we need to provide something else in this part, like the output, or can I just go to the step 3, which is to compute the evaluation metrics?

Thank you!

**Comment by aronwc** [comment]
No, you can just go to step 3.

**Comment by dougcirqueira** [comment]
Thank you very much!
