### ISSUE TITLE
Assignment3: Precision/recall curve

### ISSUE THREAD

**Issue by arunakanagaraj** [iit-cs429/main#63]
>>
For RSV, compute a precision/recall curve and plot it using matplotlib.
>>

Is precision/recall curve need to be computed for one particular query or should it cover all 83 queries? Can you please clarify on this?

**Comment by aronwc** [comment]
You should compute the average precision/recall values over 83 queries and plot the result.

**Comment by arunakanagaraj** [comment]
Ok. Thank you.
