### ISSUE TITLE
Do we keep the top line of each document?

### ISSUE THREAD

**Issue by saiarjuntanguturi** [iit-cs429/main#65]
Hi,
Do we keep the top line of each document? (for example: *TEXT 017 01/04/63 PAGE 020). Also, do we need to use the numbers written after *TEXT for our documents, or do we do it by position in TIME.ALL? Thank you!

**Comment by saiarjuntanguturi** [comment]
Oops, just read this : 
Note that IDs are assigned to queries and documents according to their position in the file, starting at ID 1. Thus, in TIME.REL, the line "1 268" indicates that the first query in TIME.QUE is relevant to the 268th document in TIME.ALL.

Still wondering about the question of whether we keep the lines with *TEXT or *FIND or *STOP?

**Comment by vivekpabani** [comment]
No, You need to remove the *TEXT and similar lines. Also ignore the blank lines. So for below lines -
-------------------------------------------------------------
*FIND      1

 KENNEDY ADMINISTRATION PRESSURE ON NGO DINH DIEM TO STOP

SUPPRESSING THE BUDDHISTS .

*FIND      2
-----------------------------------------------------------------

You should store query1 as - "KENNEDY ADMINISTRATION PRESSURE ON NGO DINH DIEM TO STOP SUPPRESSING THE BUDDHISTS ."
