### ISSUE TITLE
Assignment 3: Precision measure

### ISSUE THREAD

**Issue by dougcirqueira** [iit-cs429/main#66]
Hi,

It is oriented that we must compute the metrics for the top-20 results. In the case of precision, for example, we need to do like:
```python
precision = number_relevant_docs / 20
```
Am I right?

Thank you!

**Comment by saiarjuntanguturi** [comment]
Well for some queries you might not have 20 results.

**Comment by dougcirqueira** [comment]
It's true! Thanks for your observation @saiarjuntanguturi ! However, how about in the case when my query returns more than 20 results? I know that we need to find the relevant docs among the returned number, but as we are supposed to calculate in the top-20, does it mean that I should compute dividing by 20, when I have 20, or the total of retrieved documents?

**Comment by dougcirqueira** [comment]
The maximum possible is always 20, so I've figured it out! Thank you @saiarjuntanguturi !
