### ISSUE TITLE
How many relevant documents should I get?

### ISSUE THREAD

**Issue by gchoi5** [iit-cs429/main#71]
How many relevant documents should I get for each query?

My program only get 1 or 0 relevant document for all cases... (Cosine similarity, RSV, BM25)

**Comment by JaySurplus** [comment]
I believe it should more then 1 or 0.

**Comment by gchoi5** [comment]
I literally got 0 or 1 relevant document, almost 0 for all queries...
Is it right?

**Comment by aronwc** [comment]
There should be some queries where you find more than 1 relevant document.

**Comment by gchoi5** [comment]
Okay, I got 2 relevant document which is still very rare when I use BM25.
But still almost every precision and recall are 0...
Is it right?

**Comment by aronwc** [comment]
Probably not. You may want to check your mapping to query/doc ids.

**Comment by gchoi5** [comment]
What do you mean query/doc mapping?
Isn't every query supposed to compared with all documents?

**Comment by aronwc** [comment]
I mean how you map a query to its id. If there is an error in this logic, the .REL file would be read incorrectly, leading to almost none of the returned documents to be recognized as relevant.
