### ISSUE TITLE
Assignment #3 precision/recall curve.

### ISSUE THREAD

**Issue by canichet** [iit-cs429/main#74]
I saw a post yesterday regarding the same question, Where you told to compute the average of precision/recall values over 83 queries . So, the graph will consist of only two dots which represent the averaged precision/recall values ?

**Comment by vivekpabani** [comment]
No, the graph will contain one point each (precision, recall) for every system. So, there will be one (precision, recall) point for Cosine, and another (precision, recall) point for RSV, and so on. In total, there will be 6 points.

**Comment by canichet** [comment]
in the assignment Professor has asked to calculate precision/recall curve only for RSV .

**Comment by vivekpabani** [comment]
My bad. Please disregard the previous answer.

**Comment by JaySurplus** [comment]
You should plot over two lists.
>>>Returns two arrays containing the precisions and recalls for each returned
document.

**Comment by canichet** [comment]
but don't we have to average over those lists and then plot over those averaged values ?  that is what professor has mentioned here https://github.com/iit-cs429/main/issues/63

**Comment by aronwc** [comment]
Yes.
For each query you will get one precision vector and one recall vector. Return the average of those vectors over queries.

**Comment by canichet** [comment]
okey. So the graph will contain only two dots , right ? the averaged value of precision and recall. As you have drawn in your lectures ?

**Comment by aronwc** [comment]
No, more than two dots. If you return 20 docs, you get 20 points. Please see textbook for details.

**Comment by canichet** [comment]
ok thank you .

**Comment by dougcirqueira** [comment]
I'm considering that we have 83 values of precision and recall for RSV, which means two vectors with those values. So, we can plot the precision/curve with these two vectors. I did not understand "20 docs, 20 points", because for each query it's supposed to get one value of Precision and Recall, computed over the documents retrieved for that query. 

Is my statement wrong?

**Comment by abarbosa94** [comment]
I am having the same problem that Douglas is describing.

If someone clarify his it will be much appreciated.

**Comment by vivekpabani** [comment]
I am not sure, but just giving a try. We are considering top 20 documents for each query. 
Now, take first query result - it will have 20 documents. With each document, you can calculate the precision just like described in lecture 9.(formula - relevant_docs_so_far/retrieved_docs_so_far) 
For example, if the first document is relevant, the precision so far is 1.0,  then if second document is not relevant, then precision so far is 0.5, and if third document is relevant, precision so far is 0.66. This way, we will have 20 different values, which makes a vector. We need to find such vectors for all 83 queries, and then take average_vector of it. The same goes with recall.(So, both vectors will have 20 points each). Finally, we can make graph considering each corresponding (precision, recall) value as points.

**Comment by aronwc** [comment]
Yes!
