### ISSUE TITLE
doubt about RSV

### ISSUE THREAD

**Issue by FilipeTabosa** [iit-cs429/main#76]
I think maybe I've misunderstood something about the formula of RSV, so if someone could help me I would really appreciate.

I was trying to use the exercise from slide 12 as an example when I was writting the RSV's formula on my code.

According to the exercise 2, RSV = sum(for all queries) log (N/dfi), where N is the number of documents and dfi is the document frequency.

My point is, N and dfi are variables that will be the same for any document. So how am I supposed to choose the 20 most relevant documents?

**Comment by kvaghas** [comment]
As shown in later example, multiply by term frequency for each document.

**Comment by JaySurplus** [comment]
For each query  in query_list ,  1. compute the inverse doc_freq of the query term.   2.   If any doc in doc_list contain query , rsv score is to add doc_freq . 
```   queryList = [a , b]   doc_freq = {a : [d_1,d_2] , b : [d_1] }
    Rsv(d_1) = idf(a) + idf(b)
    Rsv(d_2) = idf(b)

**Comment by FilipeTabosa** [comment]
Thank you guys for the answers, they were helpful =).
