### ISSUE TITLE
Query regarding ShortAnswers in Assignment1

### ISSUE THREAD

**Issue by TejashreeHinge** [iit-cs429/main#80]
In Question 3, 
1) Answer for Heap's law is given as 20,000,000, But I calculated this as follows:
Total No. of tokens = 400 token per page * 400,000,000 webpages.
Hence value came out to be 40,000,000.
Can anyone please clarify why the value is 20,000,000

2) While calculating hapex legomena the equation f_i = k/i is re-written as f_i/T = k/i
Can anyone please explain this equality.

**Comment by aronwc** [comment]
1. Yes, this is an error. The answer should be 40,000,000
2. Zipf's law says f_i is inversely proportional to i, that is f_i = k/i. Since k is a constant term, we can also write f_i / T = k' / i, for some new constant k' = k / T.

**Comment by TejashreeHinge** [comment]
Thank you.
