### ISSUE TITLE
Doubt in assignment 1 solution.

### ISSUE THREAD

**Issue by gchoi5** [iit-cs429/main#81]
About the solution of the question 1-2,
before it compares (24, 89), it compares (75, 89) and (92, 89) first.

But when it compared (92, 95), it compares (92, 95) first and then (115, 95).

According to the algorithm, whether the pointer after skip is greater or not, doesn't it have to compare the given pointers first?
```python
elif docID(p1) < docID(p2):
    if hasSkip(p1) and (docID(skip(p1)) <= docID(p2)):
        while hasSkip(p1) and (docID(skip(p1)) <= docID(p2)):
            p1 = skip(p1)
```

**Comment by aronwc** [comment]
Yes, I accept either answer.

**Comment by gchoi5** [comment]
Although the number of comparisons are different?

**Comment by aronwc** [comment]
Yes, I allowed a few different interpretations of the algorithm.
