### ISSUE TITLE
Bayes Rule

### ISSUE THREAD

**Issue by saiarjuntanguturi** [iit-cs429/main#84]
Hi,

In the notes you went from the larger table to the smaller tables. How exactly did you do that? I'm not seeing the pattern. I thought you just add up the probabilities independent of the other features. for example:
x(i1) table would look like this

xi1             p(xi1| y=1)
0               0.1+0.2+0.15+0.15 = 0.6
1               0.05 + 0.05 + 0.1 + 0.2 = 0.4

I'm not sure how you obtained 0.3 and 0.7 instead. Could anyone elaborate?
Thanks!

**Comment by sjain41** [comment]
that mentioned above and also i dont get how the values are 0.1,0.2,0.15.... Please explain

**Comment by aronwc** [comment]
There's no relation between the two tables. They are just examples. The values are made up for illustrative purposes.
