### ISSUE TITLE
Assignment4: log  function to be used

### ISSUE THREAD

**Issue by gulavanir** [iit-cs429/main#86]
Should math.log10 be used even while implementing assignment 4? 
Using this function is giving "math domain error".

**Comment by gulavanir** [comment]
Also while calculating the score for a document do we have to consider the score for punctuations which are present in the token list of each document?

**Comment by aronwc** [comment]
math.log10: yes. If you're getting "math domain error," note that terms that appear in testing data but not training data can be ignores.

punctuation: yes, treat them like other tokens, as they can matter for spam classification.
