### ISSUE TITLE
Output of assignment 4 not matching

### ISSUE THREAD

**Issue by mgautham81** [iit-cs429/main#88]
I am getting different values of false spam numbers. Rather than 8 false spams as mentioned in Log.txt, I am getting the following output.

read 1893 training documents.
read 1000 testing documents.
accuracy=0.985, 10 false spam, 5 missed spam

I have checked in the latest code.

**Comment by vivekpabani** [comment]
I am also getting the same output as above. Did you find any solution for this?

**Comment by mgautham81** [comment]
No.. still looking..

**Comment by TejashreeHinge** [comment]
Make sure each of your dictionary stores float values.
And each division is of float type e.g. z = float(x) / float(y)

**Comment by vivekpabani** [comment]
Did you get the exact output? I have taken care of all float declarations, still I am getting the same output.

**Comment by TejashreeHinge** [comment]
Yes, I got the exact output.
