### ISSUE TITLE
Q1 Question 3

### ISSUE THREAD

**Issue by gchoi5** [iit-cs429/main#90]
Isn't it the same with the apple orange example in the video?

P(y=1 | apple=1, orange=0) = P(y=1) P(apple=1 | y=1) P(orange=0 | y=1)

P(y=1 | dog=1, cat=0) = P(y=1) P(dog=1 | y=1) P(cat=0 | y=1)
=0.6 * 0.2 * 0.4 = 0.048

I did it in the exactly the same way you did in the video...

**Comment by aronwc** [comment]
That's the unnormalized probability. You'll need to divide by P(y=1|dog=1, cat=0) + P(y=-1|dog=1, cat=0).
