### ISSUE TITLE
Classify function on A4

### ISSUE THREAD

**Issue by FilipeTabosa** [iit-cs429/main#91]
Hi guys, I think I did not understand right how to do calculate the score and do the Classify function. I tried to do it, but my results were the following: accuracy:  0.842 ,  2  false spam, 156  missed spam. And I don't think the problem is either in my train or evaluate function, so it must be on the Classify one.
As I am doing now, I am reading all documents, and for each document, I read all the tokens from this document, and then I assign its probability value of being a Ham and of being a Spam to two different variables (scoreHam, scoreSpam), and then I sum the logs from all my tokens on each document, like the following:

                    scoreHam[x] += math.log10((1. * self.probHam[documents[x].tokens[y]])) 

Where scoreHam and scoreSpam is the score of the document being Ham or Spam, x is the document (0,1,2...), self.probHam and self.probSpam is a dict with tokens and its probability, and documents[x].tokens[y] is each token from document[x]. 
I must be doing something wrong in calculating the score as I did not understand it exactly how it is supposed to be done, so if someone can help me I would really appreciate.

**Comment by aronwc** [comment]
Do you also include the class prior in this calculation? (e.g., P(spam) or
P(ham))

Also, please try to avoid sharing long code snippets with other students.
Instead, see if you can identify a particular aspect of the code that you
have a question about.

**Comment by FilipeTabosa** [comment]
I forgot about the class prior, that must be it, thank you. Also sorry for putting a long code there, I edited my question to put just the necessary part.
