### ISSUE TITLE
Logic

### ISSUE THREAD

**Issue by saiarjuntanguturi** [iit-cs429/main#92]
Hi,
I'm getting really bad results. Just wanted to make sure I was doing this right. So to calculate the probability of a document being spam, I would just sum the log(P(being spam)) with the logs of the conditional probabilities of each token (if that token was in the training data). Is that right?
Thanks,
Arjun

**Comment by aronwc** [comment]
E.g., if the document is "cat cat dog", you would compare:

log(P(spam)) + log(p(cat|spam)) + log(p(cat|spam)) + log(p(dog|spam))

with

log(P(ham)) + log(p(cat|ham)) + log(p(cat|ham)) + log(p(dog|ham))

where log is math.log10

-Aron

On Thu, Apr 2, 2015 at 12:16 AM, saiarjuntanguturi <notifications@github.com

**Comment by saiarjuntanguturi** [comment]
Awesome! Fixed it. Thanks.
