### ISSUE TITLE
assignment 5 clarifications

### ISSUE THREAD

**Issue by sjain41** [iit-cs429/main#93]
I am confused at how the mean works in this:
![image](https://cloud.githubusercontent.com/assets/10426532/7039344/1ff3bc36-dd86-11e4-972d-50ccdd357563.png)

I dont understand how to interpret this in terms of the documents available. Can someone explain this? I am not understanding how to start building the thought process on this? Thanks.
As i understand i have to first do compute_clusters(), then compute_means(). correct?

**Comment by aronwc** [comment]
Suppose there are two documents in a cluster:

(5, 2)
(3, 4)

Then the mean of the cluster is:

( (5+3)/2, (2+4)/2 ) = (4, 3)

-Aron

**Comment by abarbosa94** [comment]
Professor in this case, supposing two documents and the words
('a' = 2; 'b' = 3)
('a' = 1; 'c' = 1)

The mean of the cluster will be:
('a' = (2+1)/2, 'b' = 3/2, 'c' = 1/2) = ('a' = 3/2; 'b' = 3/2; 'c' = 1/2)?

Thanks !

**Comment by aronwc** [comment]
Yes, this looks correct.
