### ISSUE TITLE
a5 iters parameter.

### ISSUE THREAD

**Issue by canichet** [iit-cs429/main#94]
Professor,
I dont understand how to use iters parameters in the cluster method of kmeans.
can you please explain.

**Comment by JaySurplus** [comment]
1.At the Initialization step: choose k vectors as center of k clusters.
2.Then compute distance between all vectors and the k clusters. Assign vectors to closest cluster.
3.After assigning all vectors to cluster, then compute mean vectors of all k clusters. 
Repeat step 1,2,3  n times. n is the iters parameters.

See more detail description: [k-means clustering](http://en.wikipedia.org/wiki/K-means_clustering)

**Comment by aronwc** [comment]
This is correct, but note that initialization happens just once.
-Aron

**Comment by canichet** [comment]
so for each iteration the initial vectors for the clusters will be the same Since it is initialized only once ?

**Comment by benjaminwalters** [comment]
I think the new initial vectors are the ones calculated in step 3 of the
last iteration.

**Comment by JaySurplus** [comment]
Let me make clearly about step1:
Initialization step only happens at the  `first` iters of all n iters.  
For k-th iters(k > 1) . 
     Step1. Use the vector computed from Step3 at the pervious( k-1 th) iters as the center vector of each cluster.
     Step2. Compute distance and assign vectors to closest cluster.
     Step3. Compute mean vectors of all k clusters. (The new mean vectors will be the new center vector of each cluster in k+1 th iteration ).
