### ISSUE TITLE
Issue while printing documents

### ISSUE THREAD

**Issue by gulavanir** [iit-cs429/main#96]
Running the code (without encoding words) on command prompt or python console while printing the document contents throws following error:
 "UnicodeEncodeError: 'charmap' codec can't encode character u'\u0ad0' in position 13: character maps to <undefined>".

This happens for characters like ૐ. The same code works fine on IPython console and displays correct character.

If encoding is added (.encode('cp850', errors='replace').decode('cp850')) while printing the characters the output displays "?" instead of the actual character on command prompt, python console as well as IPython console.

Considering above cases should encoding be added in the code or not added?

**Comment by aronwc** [comment]
This problem doesn't happen for me, but character encoding is a bit of a
headache with Python 2.7. If you're using a *nix environment, try this:

export PYTHONIOENCODING=UTF-8
export LC_ALL=UTF-8

More details here:
https://wiki.python.org/moin/PrintFails

-Aron

**Comment by gulavanir** [comment]
I am running the code on Windows,Anaconda, Spyder IDE and code is running on IPython console
but failing on python console.

Should I simply keep the print statement (no encoding) as running the code in your environment will not throw any error?

**Comment by aronwc** [comment]
Yes, that should be fine.

I'm not sure how Windows handles encoding issues.

**Comment by JaySurplus** [comment]
@gulavanir   Can you specify which part of code or function generate that error?  ( I will grade the assignment).

**Comment by gulavanir** [comment]
Following line in "print_top_docs" function:
print " ".join(x for x in self.documents[docids].keys())

This happens for cluster1 letter "ૐ"

**Comment by dbajic** [comment]
Python kind of sucks with Unicode in 2.7, so you can try unicode(x).encode('utf8') and see if that fixes it.

https://docs.python.org/2/howto/unicode.html

**Comment by gulavanir** [comment]
@dbajic :  I tried that as well. The issue with it is, the error is gone but now the character is seen as
"?" instead of "ૐ"

**Comment by dbajic** [comment]
That's odd. Since you're on Windows you could possibly try the Git Bash command line and run that code to see if you still have that issue.

https://msysgit.github.io

**Comment by rkalyan1** [comment]
Even I'm getting the same problem. I'm running the code in Mac OS and Python version2.7. Any way to resolve this?

**Comment by aronwc** [comment]
@rkalyan1 please push your latest code so I can test.

**Comment by rkalyan1** [comment]
My code is not complete.. I'm having issues with even reading the text file. Getting the following error:

UnicodeDecodeError: 'utf8' codec can't decode byte 0xd1 in position 8: invalid continuation byte

**Comment by aronwc** [comment]
You can (and should) commit you code often, even if not complete.

**Comment by rkalyan1** [comment]
Okay will push it now. I was trying to re-install python and checking if it was due to any internal errors. The full error is as follows:

Traceback (most recent call last):
  File "cluster.py", line 92, in <module>
    main()
  File "cluster.py", line 84, in main
    profiles = read_profiles('profiles.txt')
  File "cluster.py", line 77, in read_profiles
    for line in infile:
  File "/Users/anaconda/lib/python2.7/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd1 in position 8: invalid continuation byte
 
Can you help me resolve this?

**Comment by rkalyan1** [comment]
Error Resolved. Problem was in the text file

**Comment by bpraveen92** [comment]
yes , you can directly download the text file using the given hyper link there's a package called urllib using which you can do this otherwise if you just copy paste the whole text into a new text file and then use it in your code then you'll be getting this unicode error.

**Comment by TejashreeHinge** [comment]
I am also getting "charmap_encode" error. I am using anaconda Spyder IDE on windows 8.
Should I submit with 'cp850' encoding to resolve the above error or submit without encoding.
However, after 'cp850' encoding, character "?" is getting displayed instead of  "ૐ". 
Which one is acceptable?

**Comment by ryanellison** [comment]
I had luck printing (on Windows) with the following:
print (u" ".join(self.documents[doc_id].keys())).encode("utf-8")

**Comment by TejashreeHinge** [comment]
I tried above encoding. I am not getting error but still character "ૐ" is not getting displayed. Instead of that "à«" character is displayed.

**Comment by aronwc** [comment]
@TejashreeHinge When I run your code without the cp850 transformation, the UTF-8 prints correctly for me. So, no need to use the cp850 bit in what you submit.

I'm guessing your error is either from how you downloaded the file or how your console handles encoding.

**Comment by TejashreeHinge** [comment]
Thank you Professor.
