### ISSUE TITLE
Function parameters

### ISSUE THREAD

**Issue by arunakanagaraj** [iit-cs429/main#97]
Is it ok to change any of the function parameters (example the parameters for distance function) of the stubs provided?

**Comment by JaySurplus** [comment]
It is not necessary but I think it is ok to do so. @aronwc

**Comment by aronwc** [comment]
It's okay, though you shouldn't need to. (You can also use instance variables as another way to access data in object methods.)

**Comment by arunakanagaraj** [comment]
Thanks
