### ISSUE TITLE
Assingment clarifications

### ISSUE THREAD

**Issue by abarbosa94** [iit-cs429/main#98]
Professor, I think that I didnt undestrand some principles of kmeans:

Suppose if I have two documents and the words
('a' = 2; 'b' = 3)
('a' = 1; 'c' = 1)

The mean of the cluster will be:
('a' = (2+1)/2, 'b' = 3/2, 'c' = 1/2) = ('a' = 3/2; 'b' = 3/2; 'c' = 1/2)?

By analogy on the first iteration of my kmeans algorithm, all my clusters will have only one document picked randomly so the mean vector will have, basically the same information about the documents. Is that right? For example, suppose if I have four documents in the world and decide to use two clusters:
Documents = ('a' = 2; 'b' = 3); ('d' = 2; 'g' = 3); ('a' = 1; 'b' = 4); ('e' = 2; 'j' = 3)

Cluster 1: ('a' = 2; 'b' = 3)
Cluster 2: ('e' = 2; 'j' = 3)

So the mean vector, in the first iteration, will be:

mean[0] = ('a' = 2/1; 'b' = 3/1) ---- 1 document in this cluster
mean[1] = ('e' = 2/1; 'j' = 3/1) ---- 1 document in this cluster

Is this correct?
However, currently, I am getting the following problem: when I compute the distances, all my documents are assigned to one cluster or to the another one (in the case of two clusters), resulting in one cluster with all documents and the other one with 0 documents.

Where is my error?

Also, one more question:

When I compute the distance between document and cluster, to compute the dot product, I first need to check if the mean vector contain a given term from the document. If yes, I compute the dot product between document and mean for this term. Is this approach correct? I remember something related to this from one of the past class.

I would be really appreciated if you, or someone else clarify those things for me.

Thanks a lot,
Andre

**Comment by aronwc** [comment]
>So the mean vector, in the first iteration, will be:
>
>mean[0] = ('a' = 2/1; 'b' = 3/1) ---- 1 document in this cluster
>mean[1] = ('e' = 2/1; 'j' = 3/1) ---- 1 document in this cluster

I assume you mean that you are initializing the first mean to document 0 and the second mean to document 3?

After this initialization, you proceed by assigning each document to its closest mean. In this example, document 1 has equal distance to both mean[0] and mean[1]. Arbitrarily assigning document 1 to cluster 1, you would have:

- cluster 0: document 0, document 2
- cluster 1: document 1, document 3

Next, you would re-compute the means of each cluster:

- mean[0] = {'a': 3/2, 'b': 7/2}
- mean[1] = {'d': 2/2, 'e': 2/2, 'g': 3/2, 'j': 3/2}

You would continue by re-assigning each document to its closest cluster, then recomputing the means. Though, I suspect that for this example k-means has converged already.

**Comment by aronwc** [comment]
>When I compute the distance between document and cluster, to compute the dot product, I first need to check if the mean vector contain a given term from the document. If yes, I compute the dot product between document and mean for this term. Is this approach correct? I remember something related to this from one of the past class.

Yes, but recall that Counter objects will return 0 if a key is not present. So, you can safely multiply each value in the document Counter by the corresponding value in the mean Counter. The dot product is the sum of these products.
