### ISSUE TITLE
Assignment 5

### ISSUE THREAD

**Issue by FilipeTabosa** [iit-cs429/main#99]
Professor, could you please postpone the assignment until Friday? 

Thank you
Regards,
Filipe.

**Comment by wenderxavier** [comment]
I'm kind of stuck in a few problems too, if could be postpone it would be great.

**Comment by adityashirodkar** [comment]
I too need an extension.

**Comment by aronwc** [comment]
OK, you win. Please turn in assignment 5 by Friday 11:59pm.
-Aron

**Comment by adityashirodkar** [comment]
Thank you professor..!

**Comment by FilipeTabosa** [comment]
Thank you professor
